### ISSUE TITLE
Completion of Forums Enhancement

### ISSUE THREAD

**Issue by e0d** [openedx/platform-roadmap#1]

**Comment by jmakowski1123** [comment]
This was a placeholder ticket and has subsequently been replaced by the following epics corresponding to BD-38:
https://github.com/openedx/platform-roadmap/issues/14
https://github.com/openedx/platform-roadmap/issues/73
https://github.com/openedx/platform-roadmap/issues/74
https://github.com/openedx/platform-roadmap/issues/75
https://github.com/openedx/platform-roadmap/issues/76
https://github.com/openedx/platform-roadmap/issues/77
https://github.com/openedx/platform-roadmap/issues/78
https://github.com/openedx/platform-roadmap/issues/79
https://github.com/openedx/platform-roadmap/issues/80
https://github.com/openedx/platform-roadmap/issues/81
https://github.com/openedx/platform-roadmap/issues/82
