### ISSUE TITLE
Visual Text Editor enhancements (BD-14)

### ISSUE THREAD

**Issue by jmakowski1123** [openedx/platform-roadmap#108]
### **Scope of the Feature**

Formerly known as the HTML Component, the newly renamed Text Component includes updates that make it even easier to include text and images in your course content. With the newly updated editor:

- Adding images becomes easier with gallery sorting

- Table authoring is enabled without going into HTML mode

- Emoticons are easier to include 

- Incorporating special characters and symbols is easier

- Undo / redo actions capability is offered

- A full-screen editing experience is enabled

Adding Images
We have made it easier to reference existing files and uploads from your course in text components. You can now sort all images as well as search and upload new images to your course as you are authoring a specific text component.

Table Tools
Another category of new tools we have added includes the addition of tables without needing to jump to the HTML editor. The table toolbar icon lets you drop in a table component and selecting a given cell lets you create, remove, or adjust rows and columns.

Emoticons
You can now also easily add emoticons into your text content. This can be  a way to break up long stretches of text content. 

Special Characters
We have also introduced a way to include special characters into your text content, including mathematical and symbolic elements.
 
Full-Screen Editing Experience
This is useful when building blocks with a large amount of content.

Future Improvements
We will be looking to improve linking to other parts of the course to eliminate the need to copy and paste jump-to-location IDs. Other improvements include in-context image editing tools including cropping and spell checking. 

Additionally, T&L has fielded partner and platform issues related to custom HTML components for many years. To increase content quality and lower our operational burden, we are removing the Raw HTML option from the Text component while still retaining a way for course teams to view and edit the source of the component through the Visual Editor. 

### Documentation details:

- Link to Product blog/demo: https://openedx.atlassian.net/wiki/spaces/OEPM/blog/2022/10/21/3560571009/2U+New+Text+HTML+Editing+Experience

- Link to "How to enable":
- Link to any other relevant technical documentation:

### Community Release Information

Product-ready details:

- Is this feature enabled by default? Is it currently enabled?
- Is this feature internationalized?
- Is this feature theme-able?
- What's the production status as of the date of the code cut-off?
- Primary contact:

------
Original documentation:
Milestone 3.4: 

Objective - Create a new React-based HTML block editor for the course authoring experience. This will enable the use of the HTML block in the upcoming v2 content libraries’ authoring experience.

Goal: Update custom text editor for the course authoring experience to use new video editor experience

Jira Milestone: https://openedx.atlassian.net/browse/TNL-9306

### Initiative-level Narrative

Building on the work done to support a new content storage engine for the Open edX platform in Blockstore, this effort is a major update of our unstructured content library authoring experience, as well as the content tagging infrastructure necessary to help organize and structure content for use and reuse in courses. While today library content only powers randomized assessments, this effort seeks to expand the use of course content reference linked to content libraries, bringing a flexible new way to author content without committing to course structure in Studio. Course teams will now be able to annotate and organize their authored content through the use of taxonomies, whose tags can be used for partner and internal classifications of our catalog objects. These tags provide a way for educators to source / reference content from content libraries into their courses, enabling the powerful versioning and reuse workflows currently only possible by managing hundreds of content libraries at a time, as MIT / Harvard do today.  
|Customer Impact|Details|
|---|---|
|Reach (Customer) |All course authors across the platform will have the ability to create content libraries and taxonomies. 
|Impact + Measure (Outcome)| Improvement to educator NPS rating & platform map competitiveness assessment (currently authoring is listed as a top 10 gap area) 
|T&L Gap Impact|(FY20 Q4 list)|Course authoring is a top 10 T&L platform gap area, and these changes will introduce a set of key requested features not available on any other top 10 competitive alternatives to Open edX’s authoring experience. |

**Comment by sarina** [comment]
Closing as this is marked "Shipped" on the PR board 🎉
