### ISSUE TITLE
Enhance Tutor so that it may replace Devstack

### ISSUE THREAD

**Issue by e0d** [openedx/platform-roadmap#11]
## Overview

The Open edX community is adopting [Tutor](https://docs.tutor.overhang.io/) as the default release technology for Open edX.  We are further exploring making tutor the default developer experience for the platform.  This work is to close known gaps between Tutor and the current Open edX Devstack to allow deprecation of Devstack and adoption of Tutor.

## The Project

This roadmap item is being tackled by a collaborative team including Tutor, tCRIL, and edX developers. Resources:
* [Early project backlog (Google Sheet)](https://docs.google.com/spreadsheets/d/12MxCu6Z3lzbF8Z6t2B39y73r65PjiwPnvwb3gHkkKD8/edit#gid=0)
* [New project tracking board (GitHub project)](https://github.com/orgs/openedx/projects/10/views/1)

**Comment by kdmccormick** [comment]
Notes from our first meeting: https://docs.google.com/document/d/1DfoCRz3xRa2kufCwP511s61f7WpX6BjZfr1OOFWzyCA/edit

**Comment by jmakowski1123** [comment]
This item served as a placeholder Initiative. The Tutor project is now underway - see corresponding Milestones for more details: https://github.com/openedx/platform-roadmap/issues/114

**Comment by kdmccormick** [comment]
All Tutor Adoption epics are now collect on this parent issue: https://github.com/openedx/platform-roadmap/issues/244
