### ISSUE TITLE
Unify the descriptor/module system (Phase 2, xBlock conversion)

### ISSUE THREAD

**Issue by e0d** [openedx/platform-roadmap#12]
This work will unify the platform’s content descriptor system and module system:

- eliminating a historically common source of difficult to diagnose memory leaks, 
- reducing redundant implementations of courseware services (e.g. course static asset linking).
- removing the single most confusing aspect of the XBlock runtime (descriptor vs. module system).

| Customer Impact  | Details  |
|---|---|
|Goal   | Development work done to modernize and simplify our core content middleware and delivery engine, migrating from our legacy xmodule system to our xblock infrastructure. |
|Reach (Customer)  | Developers making improvements to Open edX’s core content middleware layers.|
|Impact + Measure (Outcome) |Simplified development timelines and improved diagnosis of content issues will be possible by simplifying platform areas that are often poorly or not understood by internal teams.|

**Comment by kdmccormick** [comment]
Not sure if it fits into this phase, but here's one related item:
* https://github.com/openedx/edx-platform/issues/31624
