### ISSUE TITLE
Start renaming excessively long DB identifiers

### ISSUE THREAD

**Issue by e0d** [openedx/platform-roadmap#120]
A blocker for migration to MySQL 8 is long DB identifiers.

The 2U BOM team is working on changes to resolve this issue.  Their work can be tracked [here](https://openedx.atlassian.net/wiki/spaces/COMM/pages/3309469824/2022-01-27+Meeting+notes?focusedCommentId=3318218800#comment-3318218800).

**Comment by sarina** [comment]
Closing as this is marked "Shipped" on the PR board 🎉
