### ISSUE TITLE
MySQL 8 Support for Mac M1/ARM architecture

### ISSUE THREAD

**Issue by e0d** [openedx/platform-roadmap#121]
In order to support development on Mac M1 machines, we will need a workable solution for running MySQL 8 on that architecture.

The issue includes both a design proposal and the implementation.  Design proposal should be vetted by Build/Test/Release before moving forward with implementation.

Proposal should be documented as an ADR.

**Comment by ormsbee** [comment]
@e0d: I'm not sure this needs to be called out as a separate ticket for M1 Macs. There are [MySQL 8.0 docker images ARM64](https://hub.docker.com/r/mysql/mysql-server), so it should just work as part of the overall upgrade of Tutor to MySQL 8.0 when the time comes. In the meantime, M1 Macs using Tutor can continue to use MariaDB 10.4 as a stopgap.

**Comment by e0d** [comment]
Ah, got it.  What we'd need is ARM support for MySQL 1.7, which we've decided to not do in favor of MariaDB.  I'll close this if there's no objection.

**Comment by kdmccormick** [comment]
Related to https://github.com/overhangio/tutor/issues/510

**Comment by kdmccormick** [comment]
@e0d How about I close this in favor of a new Tutor project issue, something like "As a developer on on arm64 machine, I want Tutor to work out-of-the-box"?

**Comment by e0d** [comment]
Sounds good

**Comment by kdmccormick** [comment]
Closed in favor of https://github.com/overhangio/2u-tutor-adoption/issues/35

**Comment by jmakowski1123** [comment]
Reading this thread, I don't think it's appropriate to track this as shipped in Nutmeg? There's an alternate status for closed tickets (not done and not shipped).
And I think we should track https://github.com/overhangio/2u-tutor-adoption/issues/35 separately/instead on the Roadmap?
Looking to @e0d / @kdmccormick to confirm.

**Comment by kdmccormick** [comment]
Yup, I think "Closed" is appropriate here, since we never finished this, we just moved the tracking of it over to the Tutor project.

> And I think we should track https://github.com/overhangio/2u-tutor-adoption/issues/35 separately/instead on the Roadmap?

Agreed. Anyway, https://github.com/overhangio/2u-tutor-adoption/issues/35 is already nested under https://github.com/openedx/platform-roadmap/issues/122, which is on the roadmap.

**Comment by kdmccormick** [comment]
Updated the status to "Closed"
