### ISSUE TITLE
Enhanced ORAs Staff Grader

### ISSUE THREAD

**Issue by spencertiberi** [openedx/platform-roadmap#145]
### Abstract

An improved on-platform staff grading experience for ORAs (Open Response Assessments). It allows for course teams to split up work, preview student work, and assign grades all on platform. One can easily preview common file types, assign rubric values, provide comments, and coordinate grading with all members of the course teams.

### Context & Background

The previous grading experience for ORAs didn't work well with teams looking to split up grading. We found many teams downloading ORAs data, grading off-platform, and uploading grades.

### Scope & Approach

We have finished engineering at this point and this feature is live on the edX platform.

### Value & Impact

We want to measure:

- Course team satisfaction with grading
- Time spent grading

### Milestones and/or Epics

N/A as product is now live on the edX platform

### Named Release

Olive

### Timeline

N/A as product is now live on the edX platform

### Proposed By

2U/edX

**Comment by sarina** [comment]
Closing as this is marked "Shipped" on the PR board 🎉
