### ISSUE TITLE
Team ORAs

### ISSUE THREAD

**Issue by spencertiberi** [openedx/platform-roadmap#146]
### Abstract

Enables students to be organized into groups for ORA submissions.

### Context & Background

Previously, ORAs did not support multiple students assigned to groups.

### Scope & Approach

Course teams will now be able to create teams to assign ORAs to and learners will be able to collaborate on their submission.

### Value & Impact

We hope to increase learner engagement

### Milestones and/or Epics

N/A as work is finished

### Named Release

Nutmeg

### Timeline

N/A as work is finished

### Proposed By

2U / edX

**Comment by sarina** [comment]
Closing as this is marked "Shipped" on the PR board 🎉
