### ISSUE TITLE
[BD-08] Learner (B2C) Dashboard MFE conversion

### ISSUE THREAD

**Issue by Agrendalath** [openedx/platform-roadmap#147]
### Abstract

The initial goal of the project was to match parity/features on the current dashboard in a new micro front end. Additional details:
- The result would be a new MFE using the updated front-end application template, which includes a shift to using react and paragon components, that replaces the courses.edx.org/dashboard page. ([OEP-11](https://open-edx-proposals.readthedocs.io/en/latest/best-practices/oep-0011-bp-FED-technology.html) related).
- The toggles/switches necessary to switch over to using this MFE instead of the current Django view ([OEP-17](https://open-edx-proposals.readthedocs.io/en/latest/best-practices/oep-0017-bp-feature-toggles.html) related)
- The existing page includes many other features/tools, including a long list of messages that get shown as part of each course card. Being able to support these in the new MFE is something we'd like to do, though ideally through a new pattern/format than what we do today with conditionally included Django template messages.
- The sidebar has several tools/widgets, though perhaps these could be done via some form of plugin boundary (not sure which OEP to link to here, this may need some edx support as well
- As part of these we'd like to set aside some time to improve usage documentation for developers (OEP-19 related)
- Additionally, some APIs may need to be written to support the features this page uses, the details here edX can help provide but hopefully, the code can help convey much of what is necessary here.  (No existing/active OEP, but can collaborate on how to make incremental progress here as is necessary to complete this project.)
- Once the MFE exists we will want to mark the current dashboard as deprecated and do the appropriate notifications (OEP-21 related).

### Context & Background

Initially, edX planned to make this a Blended Development project - namely [BD-08](https://openedx.atlassian.net/wiki/spaces/COMM/pages/1545044047/BD-08+B2C+Learner+Dashboard+MFE+Conversion). OpenCraft prepared [the discovery document](https://docs.google.com/document/d/1HkpxLgMTB-kKoN7PjbQuUU2mARhHfIi7Zchs4ciu7vs/edit#) which outlined all use cases of the Learner Dashboard and what is missing to port them to the MFE.

### Scope & Approach

See [the discovery](https://docs.google.com/document/d/1HkpxLgMTB-kKoN7PjbQuUU2mARhHfIi7Zchs4ciu7vs/edit#heading=h.9b723bozq2y7) and its comments for the original scope and approach. It has been 2 years since then, so some of these points might have been addressed already, but many of these remarks are still relevant.

### Value & Impact

The student_dashboard is a monolithic view, which requires some data that is not currently provided by any API endpoints. By creating the smaller endpoints, fragmenting the frontend parts to separate components, and making them own their loading state ([as done in frontend-app-learning](https://github.com/edx/frontend-app-learning/blob/master/docs/decisions/0005-components-own-their-loading-state.md)) we could separate different concerns here.

### Milestones and/or Epics

TBD

### Named Release

TBD

### Timeline

TBD

### Proposed By

OpenCraft

**Comment by jmakowski1123** [comment]
As of 9/20/22, the Learner Dashboard conversion is being undertaken as a project by 2U/edx. It is targeted for deployment in edX around the first week of October.

**Comment by sarina** [comment]
Closing as this is marked "Shipped" on the PR board 🎉
