### ISSUE TITLE
Upgrade frontend framework in the monolith

### ISSUE THREAD

**Issue by e0d** [openedx/platform-roadmap#15]
Project Narrative (Summary)
Working on frontend code in edx-platform is extremely difficult today, as supported by the results of our recent developer satisfaction survey.  Unfortunately, there are still times when the right (or only) way to move forward and deliver value without significant overhead is to work in this codebase, rather than re-platforming an entire feature into a new micro-frontend.  Frontend code in edx-platform isn't going away completely anytime soon, and we still need to work with it, but there's significant drag inherent in doing so.

We believe we can address the root of this difficulty, and see the most positive impact for our investment, by upgrading a few of the core libraries which we use in frontend development at edX to the versions used by our micro-frontends. Specifically, Paragon, and through its required dependencies, React.

There are wide ranging implications.

- Paragon has seen significant investment, and upgrading will improve code reuse, a11y, brandability, consistency, and developer velocity. This isn't a typo - Paragon is 11 major versions behind in edx-platform (2.6.4 -> 13.16.4).

- React has proven to be a much faster, much more effective way for us to write frontend code, and there are a variety of features and security fixes between edx-platform's version and latest (16.1.0 -> 16.14.0). It's nearly a different framework than it was in 2017 when 16.1.0 came out, and better for it.

**Comment by kdmccormick** [comment]
This is related to, or perhaps entirely duplicated by, this edx-platform issue: https://github.com/openedx/edx-platform/issues/31616

**Comment by arbrandes** [comment]
@kdmccormick, since this is the higher-level roadmap ticket, I suggest we simply point to the edx-platform one as a subtask in the description.  @jmakowski1123, thoughts?

**Comment by kdmccormick** [comment]
I think we only need one issue. No sense in trying to keep two identical issues in sync, right?

**Comment by arbrandes** [comment]
Closing in favor of https://github.com/openedx/edx-platform/issues/31616, which in spite of having come later, contains more detail.
