### ISSUE TITLE
Dark Mode and Mobile App Navigation Improvements

### ISSUE THREAD

**Issue by e0d** [openedx/platform-roadmap#16]
A Blended Development project is currently being scoped, covering:
1. Dark Mode for Android and iOS users
2. Mobile App navigation redesign

Tentative kick-off - early Feb 2022

---
Original Opportunity Brief for Android Dark Mode
**Opportunity Objective**
To provide a better user experience for learners in the night time.

**Market Evidence**
Users who tend to learn at night time due to the absence of day-time or due to being “owls” can suffer from the light while screen in front of the eyes. Facebook, Twitter and others developed their night theme long ago in order to ease user experience. 

Can also be used for edX.org platform

**Proposal Specifics**
To develop a dark theme according to accesibility standards for web and mobile

Provide a dark-light mode control in a user profile 

**Success Measures**
(TBD) to track an increased rate of users on a platform at night time

[Source: https://openedx.atlassian.net/browse/OEROADMAP-23]

**Comment by jmakowski1123** [comment]
Work on Android Dark Mode slated for BD-51 https://docs.google.com/document/d/1hDLhwElO9-CmVpQw7HKIbaO9j0B33L-Ed1unIuonwd8/edit
