### ISSUE TITLE
Pre-alpha to fully supported MFEs for Olive

### ISSUE THREAD

**Issue by jmakowski1123** [openedx/platform-roadmap#166]
### Abstract

The following Micro-frontends (MFEs) are in a “pre-alpha” state. They exist on GitHub but are not yet supported in Tutor. Additionally, they may lack key features such as support for theming, internationalization, and path-based deployments. They are expected to be fully supported by the Olive Release:

Auth MFE: https://github.com/openedx/frontend-app-authn
Discussions MFE: https://github.com/openedx/frontend-app-discussions
Course Authoring MFE: https://github.com/openedx/frontend-app-course-authoring
ORA MFE: https://github.com/edx/frontend-app-ora-grading

### Context & Background

na

### Scope & Approach

na

### Value & Impact

na

### Milestones and/or Epics

na

### Named Release

Olive

### Timeline

na

### Proposed By

tCRIL

**Comment by sarina** [comment]
Closing as this is marked "Shipped" on the PR board 🎉
