### ISSUE TITLE
Write a Product Brief: Governance model for the Product Working Group [gov]

### ISSUE THREAD

**Issue by jmakowski1123** [openedx/platform-roadmap#175]
### Acceptance Criteria

A fully fleshed product brief that outlines the objectives, business case and scope.

**Comment by jmakowski1123** [comment]
https://openedx.atlassian.net/wiki/spaces/OEPM/pages/3476357132/Idea+Board+Project+Briefs#1.-Governance-model-for-the-Product-Working-Group

**Comment by faqir-bilal** [comment]
assign me
