### ISSUE TITLE
Write a Product Brief: List major/consistent pain points for users [pain]

### ISSUE THREAD

**Issue by jmakowski1123** [openedx/platform-roadmap#177]
### Acceptance Criteria

A fully fleshed product brief that outlines the objectives, business case and scope.

Template and document location: https://openedx.atlassian.net/wiki/spaces/OEPM/pages/3476357132/Idea+Board+Project+Briefs#3.-List-major/consistent-pain-points-for-users

**Comment by faqir-bilal** [comment]
assign me
