### ISSUE TITLE
Write a Product Brief: LTI catalog and strategy [LTI]

### ISSUE THREAD

**Issue by jmakowski1123** [openedx/platform-roadmap#180]
### Acceptance Criteria

A fully fleshed product brief that outlines the objectives, business case and scope.

Product Brief template and document home: https://openedx.atlassian.net/wiki/spaces/OEPM/pages/3476357132/Idea+Board+Project+Briefs#7.-LTI-strategy,-catalogue-as-xblock-alternative

**Comment by jmakowski1123** [comment]
Noting this overlaps with some work currently underway with the Atomic Learning Unit Initiative: https://github.com/openedx/platform-roadmap/issues/165

We have written about a dozen user stories to scope the LTI catalog feature:  https://openedx.atlassian.net/wiki/spaces/COMM/pages/3488677889/User+Stories+-+WIP

**Comment by faqir-bilal** [comment]
assign me
