### ISSUE TITLE
Gap Analysis 

### ISSUE THREAD

**Issue by jmakowski1123** [openedx/platform-roadmap#189]
### Abstract

Identify feature gaps for 3-5 primary use cases (for example: What is missing in Open edX in using at as a residential LMS solution in a higher ed setting).

### Context & Background

na

### Scope & Approach

na

### Value & Impact

na

### Milestones and/or Epics

na

### Named Release

na

### Timeline

na

### Proposed By

na

**Comment by faqir-bilal** [comment]
assign me
