### ISSUE TITLE
Build a mindmap for Use case 3: Residential where OEX functions as the university's primary LMS [prod-nar]

### ISSUE THREAD

**Issue by jmakowski1123** [openedx/platform-roadmap#193]
As part of the larger project to build a Product Narrative (https://github.com/openedx/platform-roadmap/issues/174), we chose four primary use cases around which to build a use case mind map (https://openedx.atlassian.net/wiki/spaces/OEPM/pages/edit-v2/3534520967)

The mind map 
1) identifies the primary personas who need to accomplish the use case; 
2) identifies the primary needs or tasks each persona needs to do;
3) identifies the key features or functions in order to enable the need/task to be completed

The third use case is: On-campus/matriculated, functions as the university's primary LMS.

The next steps would be to complete the three tasks for the mind map for this use case, using the template created here: https://www.mindmeister.com/map/2385779758?t=FnCLcUqgZ7

This use case also requires some competitive analysis with similar LMS providers, revolving around the question: what features are required in order to achieve parity?

**Comment by faqir-bilal** [comment]
assign me
