### ISSUE TITLE
Competitive analysis with 4-6 top vendors [prod-nar]

### ISSUE THREAD

**Issue by jmakowski1123** [openedx/platform-roadmap#195]
As part of the larger project to build a Product Narrative (https://github.com/openedx/platform-roadmap/issues/174), we would like to complete a competitive analysis with 4-6 similar LMS providers in the higher education and commercial spaces. This task includes:

- [ ] Identifying which providers to analyze
- [ ] Creating a framework for analysis that includes 1) current functionality 2) gap analysis
- [ ] Includes a view of the three primary use cases mapped for Open edX (see: #192 #194 #193)

**Comment by faqir-bilal** [comment]
assign me
