### ISSUE TITLE
Provide recordings of the group meetings

### ISSUE THREAD

**Issue by antoviaque** [openedx/platform-roadmap#200]
To allow others to attend the working group meetings asynchronously, and for transparency, it would be useful to provide video recordings of the meetings. 

This is in particular for the product working group, based on[ comments on the group meeting notes](https://openedx.atlassian.net/wiki/spaces/COMM/pages/3514040378/2022-08-016+-+Product+WG+Meeting+Notes?focusedCommentId=3520495650), but since there are many working groups, it could make sense to offer the solution found to the other groups.

**Comment by antoviaque** [comment]
@jmakowski1123 Thank you!

Should I close this ticket then, or is it useful for you to keep it open as a reminder?

**Comment by jmakowski1123** [comment]
> @jmakowski1123 Thank you!
> 
> Should I close this ticket then, or is it useful for you to keep it open as a reminder?

Let's close it since it's being tracked as done, but I'd love if you remind me from time to time in the meetings, as I already forgot to record last Tuesday :-p
