### ISSUE TITLE
Scheduled Bulk Email tool

### ISSUE THREAD

**Issue by jmakowski1123** [openedx/platform-roadmap#218]
### Product scope and features included

This new feature allows educators to pre-write common announcements in advance and schedule bulk email message to be sent at a specified date and time in the future.

Course team members with access to the bulk email tools are able to set the send date & time of their messages.

- User can select date and time for a message to send

- User can edit/delete message and send time until the message has been sent

**Documentation details:**

- Link to Product blog and video demo: https://openedx.atlassian.net/wiki/spaces/OEPM/blog/2022/10/21/3548283068/2U+Scheduled+Bulk+Email

- Link to "How to enable":
- Link to any other relevant technical documentation:

### Community Release Information

**Product-ready details:**

- Is this feature enabled by default? Is it currently enabled?

- Is this feature internationalized?

- Is this feature theme-able?

- What's the production status as of the date of the code cut-off? Enabled in edX Production as of Aug 24

- Primary contact: Claire Zhang, Kelly Buchanan

**Comment by sarina** [comment]
Closing as this is marked "Shipped" on the PR board 🎉
