### ISSUE TITLE
Build React-based video player

### ISSUE THREAD

**Issue by jmakowski1123** [openedx/platform-roadmap#221]
Unlocks final phase of work for #107 and would get BD-14 over the line.

Current status - Specs and Requirements in Discovery

- [x] User feedback (top five complaints for Studio from all users)

- [ ]  Product Approach/spec 

- [x] Mocks and wireframes are complete (link forthcoming)

- [x] Tech discovery (https://docs.google.com/document/d/1LfanPFERjtmisnY3d1OA8J01nwdicakNPM-GYivNR5I/edit#heading=h.t08930wnows7)

- [ ] Technical Requirements

Contingent on settings, but now settings is done.
Building the React player would enable remaining Bd-14 work on video editor to move from H2 to H1 roadmap (edx)

**Comment by sarina** [comment]
RFP for phase 1: https://discuss.openedx.org/t/axim-funded-contribution-react-video-player-discovery-technical-design/9970
