### ISSUE TITLE
Provide frontend configuration at run-time

### ISSUE THREAD

**Issue by jmakowski1123** [openedx/platform-roadmap#224]
### Problem

Having to rebuild containers with every configuration change is very expensive; possibly even more so than with theming changes.

### Product/Platform Value

Dynamic image configuration enables platform use-cases that would not be practical otherwise.  One example is multi-tenancy.  Another is dynamic theming.

### Acceptance Criteria

While it would not be possible to do away with build-time configuration entirely, it is possible to reduce the need for it by introducing a service that provides configuration at runtime.

### Related or in-progress work

eduNext is actively working on this, and the basic mechanism is already in-place.  It was introduced server-side via [edx-platform#30473](https://github.com/openedx/edx-platform/pull/30473) (including an [ADR](https://github.com/openedx/edx-platform/blob/f2488b10a6f7f4faca8cb8877ba95d2a386822a0/lms/djangoapps/mfe_config_api/docs/decisions/0001-mfe-config-api.rst)), and client-side via [frontend-platform#335](https://github.com/openedx/frontend-platform/pull/335).

Work is in-progress by eduNext to have all Tutor-supported MFEs use this mechanism.

* [x] https://github.com/openedx/frontend-wg/issues/103

**Comment by kdmccormick** [comment]
This is done and shipped in Olive!
