### ISSUE TITLE
[Product Pull Request] Allow delete course content in Studio only for admin users

### ISSUE THREAD

**Issue by jmakowski1123** [openedx/platform-roadmap#225]
### For Contributing Author:

This is the Primary Product Ticket for the following community contribution: Allow delete course content in Studio only for admin users

### Checklist prior to undergoing Product Review:

The following information is required in order for Product Managers to be able to review your pull request:

- [x] Explanation of the problem being solved
- [x] Description of how users will be impacted, and which users will be impacted
- [x] Screenshots or video showing the functionality or fix, before and after
- [x] Reproduction steps and/or testing steps

Only if necessary:

- [ ] If necessary, links to corresponding configuration changes
- [x] If necessary, links to corresponding enablement changes, particularly waffle/toggle status details

### Related PRs

https://github.com/openedx/edx-platform/pull/27857

-------

### For Product Manager doing the review:

What criteria should be analyzed from Product to approve a PR?

- The problem being solved by the feature or fix is clear.
- There is clarity on how the change or fix will impact the end user.
- It is clear that the change will not negatively impact users or other areas of the platform.
- The change is implemented comprehensively.
- Any changes to UI use the current, standard Paragon Design System: https://paragon-openedx.netlify.app/

**Comment by jmakowski1123** [comment]
Earlier product and community input:

Marco: https://github.com/openedx/edx-platform/pull/27857#issuecomment-955003315
Dean: https://github.com/openedx/edx-platform/pull/27857#issuecomment-1097616792
Santiago: https://github.com/openedx/edx-platform/pull/27857#issuecomment-1421515367

**Comment by jmakowski1123** [comment]
### Product Information:

Problem and users impacted:



## Description

This PR and a check to show/hide the delete button on the course content in Studio. With these changes, the delete button is only visible to the admin user one with the `CourseInstructor`  role only and will not be visible to the  `CourseStaff`  role users.

Course Outline view for the user when it has *admin* access to the course
![admin_role_user_page_view](https://user-images.githubusercontent.com/15611967/120972898-e0278500-c78b-11eb-8a96-47a6d613536e.png)

Course Outline view for the user when it has *staff* access to the course
![staff_role_user_page_view](https://user-images.githubusercontent.com/15611967/120973072-1533d780-c78c-11eb-9400-b9101db08a64.png)


## Supporting information
JIRA Ticket: [BB-5815](https://tasks.opencraft.com/browse/BB-5815)

## Testing instructions
- Login with `staff@example.com`  on `https://studio.pr27857.sandbox.opencraft.hosting/`. On this sandbox we have given the superuser privileges to  `staff@example.com`
-  Go to the setting > Course team of the  *Demonstration Course* 
-  Add `verified@example.com` as the staff for the course
-  Login from the `verified@example.com` on the studio page
-  `verified@example.com` should not be able to see the delete button on the course outline page.

Enablement/Toggle info: Behind a waffle flag automatically toggled to off.

**Comment by mphilbrick211** [comment]
Hi @cablaa77! Just following up on this to see if there's any updates?

**Comment by mphilbrick211** [comment]
> Hi @cablaa77! Just following up on this to see if there's any updates?

[Link to Brad's update](https://github.com/openedx/edx-platform/pull/27857#issuecomment-1502196802).

**Comment by sarina** [comment]
Closing as this is marked "Abandoned" on the PR board. It may always be re-opened if needed.
