### ISSUE TITLE
[Product Pull Request] fix: save scroll position on exit from video xblock fullscreen mode

### ISSUE THREAD

**Issue by jmakowski1123** [openedx/platform-roadmap#226]
### For Contributing Author:

This is the Primary Product Ticket for the following community contribution: Fix the bug that when exiting a full-screen video, the browser does not return to the correct scroll position.

### Checklist prior to undergoing Product Review:

The following information is required in order for Product Managers to be able to review your pull request:

- [x] Explanation of the problem being solved
- [x] Description of how users will be impacted, and which users will be impacted
- [ ] Screenshots or video showing the functionality or fix, before and after
- [ ] Reproduction steps and/or testing steps

Only if necessary:

- [ ] If necessary, links to corresponding configuration changes
- [ ] If necessary, links to corresponding enablement changes, particularly waffle/toggle status details

### Related PRs

**master**
 
- [ ] https://github.com/openedx/frontend-app-learning/pull/983
- [ ] https://github.com/openedx/edx-platform/pull/31061

**nutmeg**

- [ ]  https://github.com/openedx/frontend-app-learning/pull/981
- [ ]  https://github.com/openedx/edx-platform/pull/31053

**maple**

- [ ]  https://github.com/openedx/frontend-app-learning/pull/982
- [ ] https://github.com/openedx/edx-platform/pull/31055

### For Product Manager doing the review:

What criteria should be analyzed from Product to approve a PR?

- The problem being solved by the feature or fix is clear.
- There is clarity on how the change or fix will impact the end user.
- It is clear that the change will not negatively impact users or other areas of the platform.
- The change is implemented comprehensively.
- Any changes to UI use the current, standard Paragon Design System: https://paragon-openedx.netlify.app/

**Comment by jmakowski1123** [comment]
close in favor of tracking here: https://github.com/openedx/frontend-app-learning/issues/1055

**Comment by itsjeyd** [comment]
Closing.
