### ISSUE TITLE
[Product Pull Request] Make course description editable in certs

### ISSUE THREAD

**Issue by jmakowski1123** [openedx/platform-roadmap#227]
### For Contributing Author:

This is the Primary Product Ticket for the following community contribution: Make course description editable in certificates

### Checklist prior to undergoing Product Review:

The following information is required in order for Product Managers to be able to review your pull request:

- [x] Explanation of the problem being solved
- [x] Description of how users will be impacted, and which users will be impacted
- [x] Screenshots or video showing the functionality or fix, before and after
- [x] Reproduction steps and/or testing steps

Only if necessary:

- [ ] If necessary, links to corresponding configuration changes
- [ ] #279

### Related PRs

- [ ] https://github.com/openedx/edx-platform/pull/29850

### For Product Manager doing the review:

What criteria should be analyzed from Product to approve a PR?

- The problem being solved by the feature or fix is clear.
- There is clarity on how the change or fix will impact the end user.
- It is clear that the change will not negatively impact users or other areas of the platform.
- The change is implemented comprehensively.
- Any changes to UI use the current, standard Paragon Design System: https://paragon-openedx.netlify.app/

**Comment by jmakowski1123** [comment]
### Product Info from the PR (29850)

## Description

This PR makes the default description text that appears under the course title editable/configurable for certificates.

## Supporting information

**JIRA tickets:** [BB-5819](https://tasks.opencraft.com/browse/BB-5819)

## Screenshots

Creating new certificates:

![certs-editable-field-during-creation](https://user-images.githubusercontent.com/13742492/151926011-fbec7f13-7640-444d-abb4-2ee09ff90dd4.png)

## Testing instructions

1. Check out this branch and open Studio.
2. Enable certificates on the a course.
3. On clicking "Set up your certificate", you should see the additional field "Course Description".
4. Add in some text for course description and preview certificate.
5. Verify that the custom course description is shown on the certificate.

**Comment by jmakowski1123** [comment]
Product Review should be assigned to Claire Zhang.

**Comment by ProductRyan** [comment]
@czhang0912 do you have any questions about this idea? Any concerns about its effect on the user experience or if it conflicts with anything that you have planned?

**Comment by mphilbrick211** [comment]
> Hi @czhang0912! Just flagging Kelly's comment / feedback for product [here](https://github.com/openedx/edx-platform/pull/29850#issuecomment-1487004404) in the original ticket.

Hi @czhang0912 - friendly ping on this!

**Comment by czhang0912** [comment]
@mphilbrick211 @ProductRyan As Kelly mentioned, we are current in the progress building the roadmap to extract the credentials from the LMS. We would like to focus on prioritizing the existing fields and not introducing another layer of complexities. Please let me know the use cases of this feature and if is critically needed for the future support in the long run.

**Comment by pkulkark** [comment]
@e0d Sure I can answer here. This came as a requirement for one of our clients. They are no longer with us but at the time of submitting the PR it was a blocker for them. They had multiple courses and had certificates configured for each of them. While all other fields in the certificate was configurable, the course description was hard-coded. We added this to our fork of edx-platform which we use for our clients.

**Comment by jmakowski1123** [comment]
I'd like to pass this PR @santiagosuarezedunext to do a product review from a wider community perspective. Edunext has another PR in the pipeline around certificates and I believe have been actively engaging with customers around certificate needs/pain points. Once we have that input, the Core Product WG can make a final call on approval if there's no current product owner on the repo.

**Comment by mphilbrick211** [comment]
@jmakowski1123 @e0d

Hi all - linking Kelly's most [recent comment](https://github.com/openedx/edx-platform/pull/29850#pullrequestreview-1541492649) from the original PR here in case people didn't see.

**Comment by jmakowski1123** [comment]
@pkulkark I'm copying over the feedback from one of the eng reviewers on the 2U side:

_"This is still very far from viable from my perspective. I would still like to see a clear set of requirements from Product and a sense of the level of need, but from there we would also need to work through several other questions about the particulars of how this feature should work, such as:

What does the field need to support? HTML? Django templating commands? Does it have a character limit?
How would this behave in existing templates? The OSPR updates the base templates but any existing templates in live instances will need to be manually updated to support this field.
Given that it requires updating all of your current templates to support this field, operators should have the ability to disable this feature if they do not plan to support it.
I think there is probably more that would come up if we thought through the requirements for this and really laid out all of the implications. But generally speaking, I don't feel this is production-ready as a feature."_

I don't think these are insurmountable questions, but given that this request came from a single client who is no longer with you, do you have access to the market input you'd need to define to this level of detail? Likewise, that change your relative prioritization of this enhancement?

**Comment by mphilbrick211** [comment]
Friendly ping on this @jmakowski1123!

**Comment by jmakowski1123** [comment]
Given that this was initially implemented as a temporary solution until the Credentials work began, and it was initially built for the sake of one client among many, it's not a high priority enhancement to pursue now. @pkulkark If you find this creates a problem for multiple clients who may be using it without our knowledge, let me know and we can reconsider. Otherwise, closing this without pursuing for now.

**Comment by sarina** [comment]
Closing as this is marked "Abandoned" on the PR board. It may always be re-opened if needed.
