### ISSUE TITLE
[Product Pull Request] Exiting full-screen video does not return to correct scroll position

### ISSUE THREAD

**Issue by arbrandes** [openedx/platform-roadmap#229]
### For Contributing Author:

This is the Primary Product Ticket for the following community contribution: Fix the bug that when exiting a full-screen video, the browser does not return to the correct scroll position.

Video demo:

https://user-images.githubusercontent.com/17108583/222696634-af8fab5c-e97e-4f5e-b7c9-b50751727fa0.mov

### Checklist prior to undergoing Product Review:

The following information is required in order for Product Managers to be able to review your pull request:

- [x] Explanation of the problem being solved
- [x] Description of how users will be impacted, and which users will be impacted
- [x] Screenshots or video showing the functionality or fix, before and after
- [ ] Reproduction steps and/or testing steps

Only if necessary:

- [ ] If necessary, links to corresponding configuration changes
- [ ] If necessary, links to corresponding enablement changes, particularly waffle/toggle status details

### Description

When exiting full-screen video, the browser does not return to the correct scroll position.

TODO: screenshots, reproduction instructions

#### master

- [ ] https://github.com/openedx/frontend-app-learning/pull/983
- [ ] https://github.com/openedx/edx-platform/pull/31061

#### palm

- [ ] https://github.com/openedx/frontend-app-learning/pull/1118
- [ ] https://github.com/openedx/edx-platform/pull/32306

#### nutmeg

- [ ] https://github.com/openedx/frontend-app-learning/pull/981
- [ ] https://github.com/openedx/edx-platform/pull/31053

#### maple

- [ ] https://github.com/openedx/frontend-app-learning/pull/982
- [ ] https://github.com/openedx/edx-platform/pull/31055

#### olive

- [ ] https://github.com/openedx/frontend-app-learning/pull/1077
- [ ] https://github.com/openedx/edx-platform/pull/31871

### For Product Manager doing the review:

What criteria should be analyzed from Product to approve a PR?

- The problem being solved by the feature or fix is clear.
- There is clarity on how the change or fix will impact the end user.
- It is clear that the change will not negatively impact users or other areas of the platform.
- The change is implemented comprehensively.
- Any changes to UI use the current, standard Paragon Design System: https://paragon-openedx.netlify.app/

**Comment by ihor-romaniuk** [comment]
Hi @ProductRyan @arbrandes @brian-smith-tcril.

@ProductRyan, I attached a short video about fixes as you asked.
Sorry for such a short video but GitHub has a limitation about file size.

https://user-images.githubusercontent.com/17108583/222696634-af8fab5c-e97e-4f5e-b7c9-b50751727fa0.mov

Comments were fixed for PR https://github.com/openedx/edx-platform/pull/31053 and added to related PRs for other releases.

Also, I have created new PR for the olive release:
- https://github.com/openedx/edx-platform/pull/31871
- https://github.com/openedx/frontend-app-learning/pull/1077

**Comment by arbrandes** [comment]
I think we're now waiting for @ProductRyan to take a look at the video, right?  Thanks, @ihor-romaniuk!

**Comment by itsjeyd** [comment]
Hey @ProductRyan, do you have any updates on when you'll be able to get back to this review?

**Comment by ProductRyan** [comment]
@ihor-romaniuk this looks like a nice fix, thanks for contributing and bearing with us as we continue to develop our product review process. @itsjeyd this is approved from a product POV.

**Comment by itsjeyd** [comment]
Noted, thanks @ProductRyan!

@ihor-romaniuk I marked all PRs belonging to this ticket as ready for (engineering) review.

CC @mphilbrick211

**Comment by ihor-romaniuk** [comment]
Hi @itsjeyd. All PRs were updated and them are ready for review. Please take a look.

**Comment by itsjeyd** [comment]
Great, thanks @ihor-romaniuk. For frontend-app-learning, I [posted](https://github.com/openedx/frontend-app-learning/pull/983#issuecomment-1539716169) on the main PR (#983) to get the changes lined up for engineering review.

For edx-platform, CC @mphilbrick211 (just in case you hadn't seen the [latest update](https://github.com/openedx/platform-roadmap/issues/229#issuecomment-1535981605) yet).

**Comment by ihor-romaniuk** [comment]
Hello everyone.
Because of a new Open edX Palm release, I've prepared additional PRs for that. @arbrandes please add them to the PRs list:
https://github.com/openedx/edx-platform/pull/32306
https://github.com/openedx/frontend-app-learning/pull/1118

**Comment by leangseu-edx** [comment]
I left a comment on Maple pr. The rest are tested and approved.

**Comment by mphilbrick211** [comment]
Hi @leangseu-edx - just confirming that Product review is complete? Can we send to Engineering?

**Comment by leangseu-edx** [comment]
@mphilbrick211  This was approved by product before it was sent to me (engineering). Am I missing something?

**Comment by mphilbrick211** [comment]
> @mphilbrick211 This was approved by product before it was sent to me (engineering). Am I missing something?

That was my typo, @leangseu-edx - apologies for that! I still see this one is open - can it also be merged? https://github.com/openedx/edx-platform/pull/31055

**Comment by ihor-romaniuk** [comment]
@arbrandes I think we can close this roadmap because all MRs were merged and some of them were closed due to outdated edx version and no need for these changes.

Thank you all for your work!
