### ISSUE TITLE
[Product Pull Request] disable forum digest subscription section by default

### ISSUE THREAD

**Issue by jmakowski1123** [openedx/platform-roadmap#235]
### For Contributing Author:

This is the Primary Product Ticket for the following community contribution: Make course description editable in certificates

### Checklist prior to undergoing Product Review:

The following information is required in order for Product Managers to be able to review your pull request:

- [x] Explanation of the problem being solved
- [ ] Description of how users will be impacted, and which users will be impacted
- [x] Screenshots or video showing the functionality or fix, before and after
- [x] Reproduction steps and/or testing steps

Only if necessary:

- [x] If necessary, links to corresponding configuration changes
- [ ] If necessary, links to corresponding enablement changes, particularly waffle/toggle status details

### Related PRs

- [ ] https://github.com/openedx/edx-platform/pull/31459

### For Product Manager doing the review:

What criteria should be analyzed from Product to approve a PR?

- The problem being solved by the feature or fix is clear.
- There is clarity on how the change or fix will impact the end user.
- It is clear that the change will not negatively impact users or other areas of the platform.
- The change is implemented comprehensively.
- Any changes to UI use the current, standard Paragon Design System: https://paragon-openedx.netlify.app/

**Comment by jmakowski1123** [comment]
Information from the original PR:

### Current state of the feature
Initially, this feature used the [Notifier Django app](https://github.com/edx-unsupported/notifier) but was deprecated and [removed from the configuration](https://github.com/openedx/configuration/pull/6098) in favor of [edx-notifications](https://github.com/openedx-unsupported/edx-notifications). More info about this deprecation can be found in the [GitHub issue](https://github.com/openedx/build-test-release-wg/issues/22).

The edx-notifications app was not supported though, so its repository was archived and moved to [GitHub - openedx-unsupported/edx-notifications](https://github.com/openedx-unsupported/edx-notifications). Check the [deprecation ticket](https://github.com/openedx/edx-notifications/issues/253) and corresponding [discussion](https://discuss.openedx.org/t/deprecation-removal-edx-notifications-repository/6748) for details. 

### What remains in the edx-platform
The forum's initial page contains the how-to info with the notification preferences toggle:
![image](https://user-images.githubusercontent.com/47273130/208666502-dab8cc23-3838-4d31-b2ba-3da6aac8dc2d.png)


This section is responsible for toggling the "notification_pref" user preference (aka NOTIFICATION_PREF_KEY). I didn't find any usage of this preference across the platform, so I'm suggesting hiding it by default by setting the ENABLE_FORUM_DAILY_DIGEST setting default value to `False`.

The result will look like 
![image](https://user-images.githubusercontent.com/47273130/208670074-dac31003-8f44-488e-b0ab-b2d6ffbedc9a.png)

**Comment by jmakowski1123** [comment]
Needs a product review from Aamir:

Can you confirm that "notification_pref" is not used anywhere across the platform?
Do the new Discussion Forum enhancements (BD-38) change the assumptions in this PR?
Are there considerations in light of the platform notifications work that should be taken into account?

**Comment by jmakowski1123** [comment]
Aamir approved https://github.com/openedx/edx-platform/pull/31459#issuecomment-1456156347

**Comment by jmakowski1123** [comment]
@mphilbrick211 just wanted to confirm that you saw the "done" status of this one?

**Comment by sarina** [comment]
Closing as this is marked "Shipped" on the PR board 🎉
