### ISSUE TITLE
[Product Pull Request] fix: Fix for code block formatting on the post preview and published post view

### ISSUE THREAD

**Issue by jmakowski1123** [openedx/platform-roadmap#237]
### For Contributing Author:

This is the Primary Product Ticket for the following community contribution: Make course description editable in certificates

### Checklist prior to undergoing Product Review:

The following information is required in order for Product Managers to be able to review your pull request:

- [x] Explanation of the problem being solved
- [x] Description of how users will be impacted, and which users will be impacted
- [x] Screenshots or video showing the functionality or fix, before and after
- [x] Reproduction steps and/or testing steps

Only if necessary:

- [ ] If necessary, links to corresponding configuration changes
- [ ] If necessary, links to corresponding enablement changes, particularly waffle/toggle status details

### Related PRs

- [ ] https://github.com/openedx/frontend-app-discussions/pull/450
- [ ] https://github.com/openedx/frontend-app-discussions/pull/449

### For Product Manager doing the review:

What criteria should be analyzed from Product to approve a PR?

- The problem being solved by the feature or fix is clear.
- There is clarity on how the change or fix will impact the end user.
- It is clear that the change will not negatively impact users or other areas of the platform.
- The change is implemented comprehensively.
- Any changes to UI use the current, standard Paragon Design System: https://paragon-openedx.netlify.app/

**Comment by jmakowski1123** [comment]
Information from original PR:

### Description

The problem with "quote" block was found on the MFE Discussion. When we are writing a post - we can immediately see normal view for quote, with padding and left border. But in preview window - quote block appears without border, margin and padding, like a regular text. The same situation with published post
 
<img width="1860" alt="Снимок экрана 2023-02-21 в 17 29 40" src="https://user-images.githubusercontent.com/19806032/220388211-81ca379a-5b34-4ec1-876e-a2b73a8b2e8e.png">

#### How Has This Been Tested?

We made minor changes in css and checked the result in preview mode and published post

<img width="1860" alt="Снимок экрана 2023-02-21 в 17 33 38" src="https://user-images.githubusercontent.com/19806032/220388989-d762fe60-ce20-4e45-9baf-abd0300dafe4.png">

and published post

<img width="1897" alt="Снимок экрана 2023-02-21 в 17 37 07" src="https://user-images.githubusercontent.com/19806032/220390292-739f7a39-c14d-4c8f-90b4-cbd1d8770bc3.png">

#### Merge Checklist

* [ ] If your update includes visual changes, have they been reviewed by a designer? Send them a link to the Sandbox, if applicable.
* [ ] Is there adequate test coverage for your changes?

#### Post-merge Checklist

* [ ] Deploy the changes to prod after verifying on stage or ask **@openedx/edx-infinity** to do it. 
* [ ] 🎉 🙌 Celebrate! Thanks for your contribution.

**Comment by jmakowski1123** [comment]
Aamir, another discussions forum bug fix that needs product review. Looks pretty straightforward to me, please comment in this ticket when your review is complete!

**Comment by ayub02** [comment]
Proposed improvement makes sense. Please proceed with technical review.

**Comment by jmakowski1123** [comment]
cc @mphilbrick211

**Comment by mphilbrick211** [comment]
Thanks, @jmakowski1123! The PR has been merged.

**Comment by sarina** [comment]
Closing as this is marked "Shipped" on the PR board 🎉
