### ISSUE TITLE
[Product Pull Request] fix: increase grading rounding precision to avoid incorrect grades

### ISSUE THREAD

**Issue by jmakowski1123** [openedx/platform-roadmap#238]
### For Contributing Author:

This is the Primary Product Ticket for the following community contribution: increase grading rounding precision to avoid incorrect grades

### Checklist prior to undergoing Product Review:

The following information is required in order for Product Managers to be able to review your pull request:

- [ ] Explanation of the problem being solved
- [ ] Description of how users will be impacted, and which users will be impacted
- [ ] Screenshots or video showing the functionality or fix, before and after
- [ ] Reproduction steps and/or testing steps

Only if necessary:

- [ ] If necessary, links to corresponding configuration changes
- [ ] If necessary, links to corresponding enablement changes, particularly waffle/toggle status details

### Related PRs

- [ ] https://github.com/openedx/edx-platform/pull/27788

### For Product Manager doing the review:

What criteria should be analyzed from Product to approve a PR?

- The problem being solved by the feature or fix is clear.
- There is clarity on how the change or fix will impact the end user.
- It is clear that the change will not negatively impact users or other areas of the platform.
- The change is implemented comprehensively.
- Any changes to UI use the current, standard Paragon Design System: https://paragon-openedx.netlify.app/

**Comment by jmakowski1123** [comment]
Information from the original PR

Enabling the rounding in #16837 has been causing noticeable (up to 1 percentage point) differences between non-rounded subsection grades and a total grade for a course. This increases the grade precision to reduce the negative implications of double rounding.

## Jira

[OSPR-5819](https://openedx.atlassian.net/browse/OSPR-5819)

## Sandbox
https://pr27788.sandbox.opencraft.hosting/
[Direct link](https://pr27788.sandbox.opencraft.hosting/courses/course-v1:edX+DemoX+Demo_Course/progress) to the progress page (you can log in as staff).

## Testing instructions

1. Import [this course](https://github.com/edx/edx-platform/files/6571274/grades_rounding_course.tar.gz) in Studio.
1. Complete two units from there.
1. Go to the `Progress` page and see that the score without this PR is 35%. After this change, it should be 34%.

## Explanation
This course contains two subsections graded as `Homework` (weight: 75%):
1. In the first subsection, users can get 2 out of 3 points (66.67%).
1. In the second one, users can get 1 out of 4 points (25%).

In the current approach, the grades of subsections are rounded. Therefore, in this case, we're getting `(67% + 25%) / 2 / 4 * 3` (`/ 4 * 3` is because of the weight (75%)), which gives us `34.5`. This is rounded up to `35%`.

This PR changes these calculations to `(66.67% + 25%) / 2 / 4 * 3`, which returns `34.37625`, which is then rounded down to `34%`.

## Deadline
None.

## Reviewers

- [x] @arjunsinghy96 
- [ ] edX reviewer[s] TBD

## Other information
Private-ref: [BB-4210](https://tasks.opencraft.com/browse/BB-4210)

**Comment by jmakowski1123** [comment]
Additional information from the author:

Hi @ProductRyan, thank you for checking. That's correct - the subsection grades calculated by the platform are inaccurate because of the [double rounding](https://en.wikipedia.org/wiki/Rounding#Double_rounding). Therefore, we want to increase the rounding precision to produce correct results.

**Comment by jmakowski1123** [comment]
Pending edX platform wide review as of 2/23/23
@ProductRyan When that platform review is complete, please resume that thread in this ticket.

**Comment by Agrendalath** [comment]
@jmakowski1123, just checking on the status of this. Is there anything we can do to help moving this forward?

**Comment by mphilbrick211** [comment]
> @jmakowski1123, just checking on the status of this. Is there anything we can do to help moving this forward?

CC: @ProductRyan @Daniel-hershel

**Comment by ProductRyan** [comment]
@Agrendalath  sorry for the long wait here, but we want to make sure we nail this cross-platform once and for all. The Aurora team is starting to open up some capacity and @Daniel-hershel is working to build out a roadmap now that he's been on board for a few months. 

I've given Daniel all the details and he's working to incorporate it into his plans.

**Comment by ghassanmas** [comment]
MY 2Cent, 

This change can probably lead to performance issue, in a nutshell to be comre accurate you need more compute time, thus more cost _more relevant to high scale_ 

Below is a script that it shows it would add around 30%  time when grades where 100K in a row. 

Other un related issue is what would happen if instructor run compute grade by mistake of a certfication that has been already issued... this probably might not be related depening on the platform certifcation policy. 

Lastly the pattern it seems to get something in which is controversial, is just to wrap it around a feature flag, which might not be alway the prefect solution but it be comers more releavnt path _if the end goal in the frist place is just to get it to be in as quickly as possible_

**Comment by Agrendalath** [comment]
@ghassanmas, I ran this locally, and the result was `10.51%`. I also tried this with 100000 iterations, and the result was `0.99%`. For 10000000 iterations, the result was `0.09%`.
The percentage you provided means a change of `0.03477s`. For a bigger scale, the difference is `0.0249s`. Are you sure this is relevant to high scale?

> Other un related issue is what would happen if instructor run compute grade by mistake of a certfication that has been already issued... this probably might not be related depening on the platform certifcation policy.

Yes, I already mentioned this in the PR:
> This change will not affect existing persistent grades as long as they are not re-generated. Otherwise, this can cause up to a 1 percentage point difference in the results (on a rare occasion, like the one described in the PR).

The current results generated by Open edX are inaccurate, though. It could be better to call this a `fix` instead of a `feat`.

**Comment by ghassanmas** [comment]
> @ghassanmas, I ran this locally, and the result was 10.51%. I also tried this with 100000 iterations, and the result was 0.99%. For 10000000 iterations, the result was 0.09%.
> The percentage you provided means a change of 0.03477s. For a bigger scale (10M rows), the difference is even smaller (0.0249s). Are you sure this is relevant to high scale?
> 
> 
I need to give a another look, it also definilty would vary from machine to machine, intel vs ARM...etc, it was just one guess.

> Yes, I already mentioned this in the PR:

Yes It was suffienct, I didn't meant to remention it, but rather there might be probably cases where an insturctor need to consider what those in case:  _where a student had a passing grade and then after this changes they get fail or vis-versa, I  speculate_ there might be buecray dpeending on the program, org author..etc of the a course. Again I am just speculating

**Comment by mphilbrick211** [comment]
Thanks, @Daniel-hershel!

**Comment by mphilbrick211** [comment]
Hi @Daniel-hershel - following-up to see if there's any update here?

**Comment by jmakowski1123** [comment]
@mphilbrick211 Let's move this PR to draft mode until we can find an owner to drive product specs for a platform-wide solution to rounding issues in grading.

**Comment by Agrendalath** [comment]
@jmakowski1123, @mphilbrick211, is there something we can do to help move this forward?

**Comment by mphilbrick211** [comment]
@Agrendalath thanks for the ping! I'm checking internally with Jenna on your questions.

**Comment by jmakowski1123** [comment]
Hi @Agrendalath . Since the implementation of this would need to take into consideration a broader platform perspective, this will need to go through the Product Review process, documented [here](https://openedx.atlassian.net/wiki/spaces/OEPM/pages/3883302913/The+Open+edX+Product+Review+Process). Per [Daniel's comment](https://github.com/openedx/platform-roadmap/issues/238#issuecomment-1520781477) (which I agree with), does your team have the bandwidth to take on defining a spec and implementing with the wider scope in mind?

**Comment by Agrendalath** [comment]
@jmakowski1123, according to [this comment](https://github.com/openedx/edx-platform/pull/16837#issuecomment-352329376), the value calculated in the `edx-platform` was meant to be the single source of truth regarding these calculations. We can verify this for the whole learner experience and gradebook, but we don't use the credentials and data backends (I thought the Analytics were already deprecated anyway?). Would this approach work here?

**Comment by jmakowski1123** [comment]
That sounds right. Axim can pick up the Credentials analysis.

**Comment by hurtstotouchfire** [comment]
@jmakowski1123 FYI the Credentials IDA should be a dumb consumer of Grades. If I had my way it would be a string and not even a number. We only need it to display the grade on the certificate and we are in no way an authority on grades. There are many Credentials bugs that have come from trying to be too smart about grades. The credentials app within edx-platform likely has more squishy boundaries, but again it is not a good thing. Just wanted to caution about any approaches that involve pushing grade precision knowledge further into the credentialing apps. I believe Ed and Glib and other credentials enthusiasts would agree with this but we can discuss if needed.

**Comment by Agrendalath** [comment]
@jmakowski1123, we have analyzed the impact of this change on the learner experience and opened https://github.com/openedx/frontend-app-learning/pull/1397 to match the calculated weighted grades of individual assignment types (on the Progress page) with the scores calculated by the LMS.

<details><summary><b>Before</b></summary>
<img src="https://github.com/openedx/platform-roadmap/assets/3189670/4d18fee1-6fc2-470b-ba88-bd4026ecbb1a">
</details>

<details><summary><b>After</b></summary>
<img src="https://github.com/openedx/platform-roadmap/assets/3189670/9290b716-7fe3-4365-a6d5-358d8f38fc8a">
</details>


The original PR (https://github.com/openedx/edx-platform/pull/27788) did not require any further changes. The only learner-facing change is that the grades will be displayed with increased precision on the legacy Progress page when a learner hovers over the subsections on the progress graph.

<details><summary><b>Before</b></summary>
<img src="https://github.com/openedx/platform-roadmap/assets/3189670/87c005ee-7ddc-4cd9-a7d3-b882f194eb3d">
</details>

<details><summary><b>After</b></summary>
<img src="https://github.com/openedx/platform-roadmap/assets/3189670/e1825437-934e-40ba-9e97-03e09371ff09">
</details>


Regarding the Gradebook, after this change (in the edx-platform), the subsection scores will have increased precision. For example, instead of 67%, it will be 66.67%. I'm not sure if this is intended, but [this line](https://github.com/openedx/frontend-app-gradebook/blob/39bff6e2765f356044d0df2714f1a533a4e99dfe/src/data/selectors/grades.js#L154) indicates that these scores should indeed be rounded to two decimals. We can change it to hide the decimal points or keep it as-is to make the scores more verbose for the Instructors. What do you think?


<details><summary><b>Before</b></summary>
<img src="https://github.com/openedx/platform-roadmap/assets/3189670/10ac0a53-2aff-4a4a-bea9-75573004593c">
</details>

<details><summary><b>After</b></summary>
<img src="https://github.com/openedx/platform-roadmap/assets/3189670/11de4120-e3da-49bc-bea5-c3c1364fd94d">
</details>

**Comment by Agrendalath** [comment]
@jmakowski1123, this is ready for the product review.

cc: @mphilbrick211, @itsjeyd

**Comment by itsjeyd** [comment]
CC @ali-hugo ⬆️

**Comment by ali-hugo** [comment]
@itsjeyd I don't _think_ this update would require more than one reviewer (which means we wouldn't really need a coordinator). However, I would like to check this in the next Core Product meeting on 30 July.

@Agrendalath To make sure I start off on the right foot, are these the steps I need to follow to review this:
1. Follow the testing instructions listed [here](https://github.com/openedx/platform-roadmap/issues/238#issuecomment-1441915405)
2.

**Comment by itsjeyd** [comment]
Sounds good, thanks @ali-hugo!

And just to understand better: I see you already marked this ticket as done. Since the July 30 meeting hasn't happened yet, what does that mean for the status of the product review process?

CC @Agrendalath

**Comment by ali-hugo** [comment]
> I see you already marked this ticket as done.

@itsjeyd I have no idea how I did that - it was a mistake! I have reopened it.

**Comment by Agrendalath** [comment]
@ali-hugo,
> Is there a sandbox or similar where I can see the change in action?

There [used to be a sandbox for this PR](https://github.com/openedx/edx-platform/pull/27788#issuecomment-1785658365), but it doesn't seem to be working anymore. @gabor-boros, do you know if we have a simple way to prepare one with https://github.com/openedx/edx-platform/pull/27788 and https://github.com/openedx/frontend-app-learning/pull/1397?

In any case, I described all impacted platform areas in [this comment](https://github.com/openedx/platform-roadmap/issues/238#issuecomment-2132456349).

**Comment by ali-hugo** [comment]
@Agrendalath @gabor-boros 
> In any case, I described all impacted platform areas in https://github.com/openedx/platform-roadmap/issues/238#issuecomment-2132456349.

In that case, don't worry about the sandbox. I should have everything I need in that comment. Thanks!

**Comment by ali-hugo** [comment]
@jmakowski1123 I've reviewed the changes outlined in [this comment](https://github.com/openedx/platform-roadmap/issues/238#issuecomment-2132456349) and everything looks good to me from a product perspective. The changes have been made taking a broader platform.

However, there is a question that I can't answer, namely:

> Regarding the Gradebook, after this change (in the edx-platform), the subsection scores will have increased precision. For example, instead of 67%, it will be 66.67%. I'm not sure if this is intended, but [this line](https://github.com/openedx/frontend-app-gradebook/blob/39bff6e2765f356044d0df2714f1a533a4e99dfe/src/data/selectors/grades.js#L154) indicates that these scores should indeed be rounded to two decimals. We can change it to hide the decimal points or keep it as-is to make the scores more verbose for the Instructors. What do you think?

Should the two decimal points be shown on the Gradebook, or should they be hidden?

**Comment by ali-hugo** [comment]
@itsjeyd A quick update on this:

> @itsjeyd I don't think this update would require more than one reviewer (which means we wouldn't really need a coordinator). However, I would like to check this in the next Core Product meeting on 30 July.

Unfortunately, there was no time to ask about this in the Core Product Meeting yesterday as there were two presentations scheduled. That said, I'm pretty sure that my review, along with @jmakowski1123's answers to my questions [here](https://github.com/openedx/platform-roadmap/issues/238#issuecomment-2257781320), will be sufficient.

I know this isn't really your "domain", but do you have any idea why this ticket's status may have been set to "abandoned"?

**Comment by itsjeyd** [comment]
@ali-hugo Sorry for the delayed reply. Scrolling up on this ticket, I found this:

![sometimes-a-bot-is-to-blame-and-not-the-gardener](https://github.com/user-attachments/assets/aa9b60cf-ced0-4e8e-971b-1ca56efa1d9f)

So it looks like there is some automation in place that updates statuses on both the Contributions board and the Open edX Roadmap when someone closes an issue. Which makes sense, but unfortunately the automation doesn't seem to make any additional updates when the issue gets reopened:

![and-its-lazy-too](https://github.com/user-attachments/assets/5dae4cb6-31fb-4dd5-a059-bc5f76fc05eb)

I went ahead and reverted the status manually on the Contributions board. Couldn't do the same for the roadmap as I don't seem to have permission to change ticket statuses there.

CC @jmakowski1123 

--

> Unfortunately, there was no time to ask about this in the Core Product Meeting yesterday as there were two presentations scheduled. That said, I'm pretty sure that my review, along with @jmakowski1123's answers to my questions https://github.com/openedx/platform-roadmap/issues/238#issuecomment-2257781320, will be sufficient.

Sounds good, thanks for the update!

**Comment by jmakowski1123** [comment]
Thanks for the before and after data and for driving the check on this. What was the rationale for including the more precise grade for learners when they hover over the progress bar? I'm questioning whether that should be presented to learners, especially if the additional decimals are hidden from course teams in the gradebook.

**Comment by Agrendalath** [comment]
@jmakowski1123,
> What was the rationale for including the more precise grade for learners when they hover over the progress bar?

As you can see [in the PR](https://github.com/openedx/edx-platform/pull/27788), we didn't explicitly change anything on the Progress page. Both the Progress and Gradebook pages were designed to show more precise grades:
> Regarding the Gradebook, after this change (in the edx-platform), the subsection scores will have increased precision. For example, instead of 67%, it will be 66.67%. I'm not sure if this is intended, but [this line](https://github.com/openedx/frontend-app-gradebook/blob/39bff6e2765f356044d0df2714f1a533a4e99dfe/src/data/selectors/grades.js#L154) indicates that these scores should indeed be rounded to two decimals.

We only increased the precision of the values passed to these pages.

**Comment by Agrendalath** [comment]
@jmakowski1123, is there anything we should discuss before moving this forward?

cc: @ali-hugo, @itsjeyd

**Comment by jmakowski1123** [comment]
Got it. I think this is ok to move forward, thanks

**Comment by itsjeyd** [comment]
@jmakowski1123 @mphilbrick211 It looks like this is done; the PR for it (https://github.com/openedx/edx-platform/pull/27788) has been merged. Can we close this ticket and move it to Shipped on the [roadmap](https://github.com/orgs/openedx/projects/4/views/20)?

**Comment by itsjeyd** [comment]
Thanks for the quick follow-up @feanil!

It looks like the bot is moving roadmap tickets from Shipped to Abandoned. Do you know why that is? Doesn't seem like the right thing to do in this context, but maybe I'm missing something.

![confused-bot](https://github.com/user-attachments/assets/d1a8e3cf-a0cb-4647-9673-27db16a2430f)

CC @jmakowski1123 @mphilbrick211

**Comment by itsjeyd** [comment]
@feanil Ah OK, so what you're saying is that in order to keep this workflow from being triggered for other roadmap tickets in the future, we'll have to close them first and then mark them as Shipped on the roadmap. Right?

As for keeping the workflow, it seems like it would need to be updated to only run upon closing a ticket that's incomplete. (But again, maybe I'm missing some relevant context on the product review process.)

@jmakowski1123 What do you think?

CC @mphilbrick211
