### ISSUE TITLE
[Placeholder] Expand ORA rubric

### ISSUE THREAD

**Issue by jmakowski1123** [openedx/platform-roadmap#252]
Including expansion of peer-grading tracking: allow instructors to obtain deeper information about which students are in which phase of the peer grading process

Enable equal weighting by peers and by course teams

**Comment by ProductRyan** [comment]
We also have requests to include a RANGE option for rubric scoring, similar to Canvas:
https://community.canvaslms.com/t5/Instructor-Guide/How-do-I-add-a-rubric-in-a-course/ta-p/842

**Comment by jswope00** [comment]
I came here to offer more ideas but if Ryan's ideas above are implemented then I think that solves a lot. What I hear is the need for is a simple, intuitive "open submission" component. There _is_ "staff-graded only" option for ORA but adding a range option and allowing inline commenting allows graders to easily accept submissions and grade them in a way that is intuitive to them, especially for small courses or for small cohorts of student (like only the verified track students, for example). 

Some additional wishlist items: 
- I'd like a way to allow "group project" submissions. So only one member needs to upload but all group members get the same grade. 
- More notifications (Similar to Colin's notes in Slack)
- - Submission notifications to faculty
- - Reminders to students to complete peer grading
- - "Grade has been received" notifications to students

**Comment by jmakowski1123** [comment]
@marcotuts These enhancements are being tracked individually on the [ORA board](https://github.com/orgs/openedx/projects/52/views/1), where each ticket should be up to date. Edunext is making progress on some of these, others don't have an owner:

More flexibility on weighting: https://github.com/openedx/edx-ora2/issues/1971

Better insights into peer grading processes (partially tackles): https://github.com/openedx/edx-ora2/issues/1975

Range grading: https://github.com/openedx/edx-ora2/issues/1968

Copy/paste rubrivs: https://github.com/openedx/edx-ora2/issues/1967

Better comment features: https://github.com/openedx/edx-ora2/issues/1945

**Comment by jmakowski1123** [comment]
closing in favor of using the ORA board
