### ISSUE TITLE
Improvements to Studio Home UI, Phase 1

### ISSUE THREAD

**Issue by jmakowski1123** [openedx/platform-roadmap#256]
### At-A-Glance

Make the Studio Home UI easier to navigate, clearer navigation pathways by persona, easier to manage lists of course runs, and easier to glean information about courses at a glance.

### Child PRs

- [ ] https://github.com/openedx/frontend-app-course-authoring/pull/846
### More information

**Product specs**

- Product brief: https://openedx.atlassian.net/wiki/spaces/OEPM/pages/3767107616/Product+Brief+Studio+Home+Redesign

- MVP specs: https://openedx.atlassian.net/wiki/spaces/OEPM/pages/3840868428/MVP+Studio+Home+Enhancements

**Design files**

- https://www.figma.com/file/RDsCFF54oD8cbSLRoLKOCw/Studio-Home?type=design&node-id=163-13934&mode=design&t=BZluPPW9HSfX38Y3-0

**Kanban board** 

### Stakeholders

Primary Contributors

- edX
- edunext
- Axim Collaborative

### Community release milestones

- **Quince:** 

- **Redwood:** Will be released

### How to contribute

- [ ] Has a community backlog with work to pick up?

**Comment by jmakowski1123** [comment]
@bryan-kersten's team is thinking through a Studio redesign. 2U should drive this

**Comment by jmakowski1123** [comment]
Spanish scope - Studio homepage upgrades to nav

Next steps - align the spanish use case to Studio homepage MFE

**Comment by felipemontoya** [comment]
Case for the Spanish use in campus for this feature.

**Abstract**

The overall interface of Studio is very inconvenient when dealing with a large number of courses or libraries.
Thinking of campus authors with large ammounts of courses and libraries in the homepage of studio, the requirement for them would be to make that page deal with large lists much better.

This includes:
- pagination
- filtering (by name, org, course ID, active/archived courses)
- sorting (by name, org, course ID)

The same improved listing capabilities would apply to libraries.


**Context & Background**

With the context of the modernization of the complete UI and the conversation held on the first meeting with bkersten@2u.com and bbrown1@2u.com we are aligned that the best way forward would be the creation of a MFE to handle the Studio Homepage. A second meeting will be held tomorrow for further steps.


**Scope & Approach**

From the Spanish campus initiative I think the scope could cover the creation of a new MFE with the necessary connections to reach parity with the current page. This means the MFE would also require that the "New course" and "New library" forms are accounted for.


**Value & Impact**

I don't have a great data driven metric, but from what I can see the value would be:

- Move from old code to react UI
- Improved User Experience for authors
- A side effect for "superusers" in large instances is that around 30k total courses in the platform the rendering of the page for a superuser timesout thus removing the capability of creating new courses or libraries.


**Milestones and/or Epics**

Milestone 1: Creation of a skeleton MFE for studio-home.
Milestone 2: Reach feature parity for display and new course form.
Milestone 3: Addition of Filters and sorting capability.


**Named Release**

With a good pace this MFE could be experimental for Quince and properly supported with BRT and all for Redwood.



**Proposed By**

Spanish OpenedX for Campus Project

**Comment by jmakowski1123** [comment]
This is being delivered via the Studio Redesign project, being driven by Mike Leery at 2U.

1. Inclusive collaboration on a [design sprint](https://www.figma.com/file/TsYHbwvzHU6tQhzh1qmwKd/Studio-Home%3A-Data-%26-Research?type=whiteboard&node-id=0-1&t=Zl3w6ZRwQcH5vm1R-0) will land on alignment on specs for Studio Home page - target mid-June
2. Implementation plan TBD

**Comment by jmakowski1123** [comment]
Status update 7/20: Design sprint held on 7/12 with representatives from 2U, Axim, OC and edunext. Landed on a list (by vote) of top ideas to implement. Jenna and Brad to prioritize that list into an MVP spec and subsequent releases. Target timeline for spec end of July. 2U will then create lofi frames and put through the UI/UX Working Group for feedback to ensure they meet the edunext/Spanish needs.

**Comment by jmakowski1123** [comment]
@felipemontoya Question about the specs you have here for the sort and filter functionality:

filtering (by name, org, course ID, active/archived courses)
sorting (by name, org, course ID)

**Comment by felipemontoya** [comment]
Hello @jmakowski1123 thanks for the clarification questions. Let's see:

1. Yes, name is the title. I call it name, because "Course Display Name" is how it appears in the studio advanced settings. There is a course name value that can be set upon creation but that can't be updated and "Course Display Name" overrides it.

2. This refers to the Org of the course. If we were filtering as free text on the courseID field this would partially solve it already. However taking it one step further it would be great to be able to filter by the organization long name and not only the short name used for the course Id. E.g ASU is the short name, but writing `arizona` should match as the long name would be `Arizona State University`

3. Yes, filtering by free text and having this match the courseID string would be a nice way of accomplishing this goal.

4. I think the status of a course goes from `unpublished` to `published`/`active` and when the course dates run out then it gets `archived`. The request by the spanish universities is only to add the filtering without removing the active/archived separation. I think having a filter by status is enough. If we later maintain the 3 status in the future or even more possible status arise (publisher comes to mind) then the filter should pick them up. Would this suffice for the use cases you have in mind?

**Comment by jmakowski1123** [comment]
Update 8/16

MVP Spec has been defined: https://openedx.atlassian.net/wiki/spaces/OEPM/pages/3840868428/MVP+Studio+Home+Enhancements

UX/UI work has started, being driven by 2U

Plan to present frames at the UX/UI Working Group meeting on 9/7

**Comment by felipemontoya** [comment]
After the first big transformation was made by the team at 2U (thanks a lot for that) we are now able to get started on some of the next steps.

As we will be doing some incremental updates, but don't have the project scope to take it all the way to the figma design, I made a wiki page detailing what our current plan is.

https://openedx.atlassian.net/wiki/spaces/OEPM/pages/4032856101/Studio+Home+incremental+upgrades+-+product+approach

@jmakowski1123 @santiagosuarezedunext please let me know all the comments and feedback you might have.
Jenna do you think we need some early engineering review on the approach there?
