### ISSUE TITLE
scores for each section are averaged across all grades received

### ISSUE THREAD

**Issue by jmakowski1123** [openedx/platform-roadmap#261]
Make the grading policy flexible so that different grading strategies can be selected.  Strategies for questions that support multiple submissions would include:

- Highest grade
- Last grade
- Average of all submissions

**Comment by felipemontoya** [comment]
This is one of the Spanish requirements regarding grades.

As it stands this would be scoped to the regular xmodule problems or capa problems when the authors configure the problem to have multiple attempts.

A similar request was made for ORA problems (the different grades from the steps), but I think it would be better to handle that separately.

---

Now, looking a bit ahead into the implementation of this the average of all submission strategy would also require that the "Student Module History" is correctly configured and available. It could be simple to only offer that strategy when the Flag for the history is also active.

**Comment by mariajgrimaldi** [comment]
Hi folks. I left a few questions for you here: https://github.com/openedx/edx-platform/pull/33911#issuecomment-1971627881. I hope to get input soon before merging.

**Comment by jmakowski1123** [comment]
dupe ticket
