### ISSUE TITLE
Integration points for use with Student Information Services and reference implementation

### ISSUE THREAD

**Issue by Kelketek** [openedx/platform-roadmap#264]
### 1. Is there an existing issue for this?

- [X] I have searched the existing issues

### 2. What new feature or functionality would you like to request?

API endpoints and models should be created to assist in management of learners via Student Information Services. A reference plugin to at least one popular or (preferably) open source student information service should be built.

### 3. What product area does this feature affect?

LMS (not listed above)

### 4. Please describe the scope of the feature

The platform should be able to synchronize information such as grades and enrollments with student information services. This would allow institutions to incorperate the platform's grading into their transcripts and overall workflow without a lot of extra manual intervention.

### 5. Please describe why you see a need for this feature

The lack of fit with the platform into institutions' existing tooling is a significant roadblock for adoption.

### 6. Please describe the potential impact and/or value of this feature

More institutions would be able to leverage the platform for the blended learning use case.

### 7. Please provide 2-3 use cases and/or user stories in support of this feature

As an instructor, I want to compile grades from the platform into my central gradebook so that I can factor scores into a final grade comprised of all assessment sources, off-platform and on.

As a learner, I want to be able to take some courses from my preferred learning institution online so that I can make more efficient use of my time.

As an school administrator, I'd like to have transcript records easily compiled and accessed to make sending and receiving them easier when my instructors use the platform.

**Comment by ProductRyan** [comment]
FYI - https://github.com/openedx/registrar

**Comment by jmakowski1123** [comment]
Can build on current work to integrate SF

**Comment by jmakowski1123** [comment]
Step 1: Build out a SF integration, which is being done by ASU. Tracked here: https://github.com/openedx/platform-roadmap/issues/267

**Comment by jmakowski1123** [comment]
Closing in favor of tracking at the epic level, starting here: https://github.com/openedx/platform-roadmap/issues/267
