### ISSUE TITLE
Course and Library import should accept .zip files in addition to .tar.gz

### ISSUE THREAD

**Issue by ormsbee** [openedx/platform-roadmap#285]
### Background

The Import pages for Course and v1 Libraries (the current default Library experience) only accept `.tar.gz` files. Zip files are more commonly used on MacOS and Windows, and the Python standard library has support for this type. We should accept Zip files as well.

![Image](https://github.com/openedx/platform-roadmap/assets/41625/df84337e-6fe9-4c06-8f8f-b456011a2d60)

### Motivation

* Zip files are more commonly used on MacOS and Windows, and can be created via right-clicking after changes are made, rather than using the command-line.
* It makes things easier for courses authored in a GitHub repository, since an entire GitHub repo can be downloaded as a zip file.

### Acceptance criteria:

* The UI should indicate that the user can upload either `.tar.gz` or `.zip` files.
* The backend import code should be updated to properly accept and decompress .zip files.
* Exports should continue to generate .tar.gz files as they do today (i.e. don't break backwards compatibility).

### Testing notes

A common workflow will be for someone to download the existing course to their local machine, decompress it, edit a number of files, re-compress the folder, and then upload. Because of this:

* The code should handle whatever Zip file is generated when you right-click-and-compress something from the OS UI. (I don't know if it generates a sub-folder or not.)
* We should be able to gracefully handle cases where there are spaces in the folder name, since they're often going to be named things like "course 7", "course 8", as they keep downloading over time.

**Comment by Agrendalath** [comment]
Resolved by https://github.com/openedx/edx-platform/pull/34191.
