### ISSUE TITLE
Copy/paste parts of the course

### ISSUE THREAD

**Issue by jmakowski1123** [openedx/platform-roadmap#289]
### At-A-Glance

The copy & paste feature lets authors copy parts of the course outline to a clipboard. Once copied to the clipboard, the content can be pasted, either in the same course or a different course. This feature will be released incrementally, first with copy/paste of component xblocks, then units, then sections.

### More information

**Product specs**

- Product Requirements: https://openedx.atlassian.net/wiki/spaces/OEPM/pages/3575513119/Approach+Memo+Studio+Copy+Paste+for+Content+Reuse+Across+Courses

**Design files**

- https://www.figma.com/file/y2qfzidTxxfYK8ONgyT7KP/Copy-Paste-Wireframes?type=design&node-id=823-778&mode=design&t=GY4jixIjvcCbmHV5-0

**Kanban board** 

- https://github.com/orgs/openedx/projects/36/views/1

### Stakeholders

Primary Contributors

- Axim Collaborative
- OpenCraft

### Community release milestones

- **Palm:** V1 released, copy/paste xblock components
Release notes: https://openedx.org/blog/introducing-copy-paste-for-course-components/

- **Quince:** V2 to be released, copy/paste units

- **Redwood:** 

### How to contribute

- [ ] Has a community backlog with work to pick up?

**Comment by sarina** [comment]
Closing as this is marked "Shipped" on the PR board 🎉
