### ISSUE TITLE
Enhancements to Teams to make learner grouping more flexible

### ISSUE THREAD

**Issue by jmakowski1123** [openedx/platform-roadmap#302]
Proposal: https://openedx.atlassian.net/wiki/spaces/COMM/pages/3885334531/Enhancements+to+Teams+to+make+learner+grouping+more+flexible

**Proposal review status:**

Contributing Product Manager: Felipe

WG Coordinator: Jenna
Reviewers (3, including the repo owner): Daniel, Jenna, Matt

Timeline: All feedback in by Nov 15, 2023

**Comment by ProductRyan** [comment]
This has product approval from @Daniel-hershel via a comment on
https://openedx.atlassian.net/wiki/spaces/COMM/pages/3885334531/Enhancements+to+Teams+to+make+learner+grouping+more+flexible 

Stipulation that it is an optional configuration that is disabled by default.

**Comment by mariajgrimaldi** [comment]
Here's the PR for the implementation: https://github.com/openedx/edx-platform/pull/33788

**Comment by jmakowski1123** [comment]
Dupe ticket, closing
