### ISSUE TITLE
Configurable grading strategy for peer assessments

### ISSUE THREAD

**Issue by jmakowski1123** [openedx/platform-roadmap#303]
Proposal: https://openedx.atlassian.net/wiki/spaces/COMM/pages/3891462181/Configurable+grading+strategy+for+peer+assessments

**Proposal review status:**

Contributing Product Manager: Felipe

WG Coordinator: Chelsea
Reviewers (3, including the repo owner): Daniel, ?, ?

Timeline: All feedback in by Nov 15, 2023

**Comment by crathbun428** [comment]
This has been reviewed by myself, Jenna Makowski, and Dave Ormsbee gave a brief technical review.

**Comment by jmakowski1123** [comment]
dupe ticket
