### ISSUE TITLE
Configurable priorities and weights for assessment steps

### ISSUE THREAD

**Issue by jmakowski1123** [openedx/platform-roadmap#305]
Proposal: https://openedx.atlassian.net/wiki/spaces/COMM/pages/3891888130/Configurable+priorities+and+weights+for+assessment+steps

**Proposal review status:**

Contributing Product Manager: Felipe

WG Coordinator: Chelsea
Reviewers (3, including the repo owner): Daniel, ?, ?

Timeline: All feedback in by Nov 15, 2023

**Comment by santiagosuarezedunext** [comment]
@jmakowski1123 This proposal can be archived because it was identified that a large refactor would be required to implement it and it is out of scope

**Comment by crathbun428** [comment]
@santiagosuarezedunext - I see this proposal was archived in confluence. Does it make sense for me to throw this to the On Hold status? Open to closing if this is so off the table it doesn't make sense to put in On Hold. Let me know what you think. Thanks!

**Comment by crathbun428** [comment]
Closing this issue because a large refactor would be required to implement it and it is out of scope.
