### ISSUE TITLE
New ways of restricting access to subsections

### ISSUE THREAD

**Issue by jmakowski1123** [openedx/platform-roadmap#312]
Proposal: https://openedx.atlassian.net/wiki/spaces/OEPM/pages/3933601858/New+ways+of+restricting+access+to+subsections

**Comment by santiagosuarezedunext** [comment]
Publicación en Discuss: https://discuss.openedx.org/t/new-ways-of-restricting-access-to-subsections/12643
Publicación en Slack: https://openedx.slack.com/archives/C057J2D1WU9/p1711578798337229

**Comment by santiagosuarezedunext** [comment]
@jmakowski1123 This proposal can be archived because it was made using an xblock and it is not necessary to take it to product review

**Comment by crathbun428** [comment]
Closing this since this will be solved via xblock.
