### ISSUE TITLE
Option to reimplement legacy course breadcrumb navigation

### ISSUE THREAD

**Issue by jmakowski1123** [openedx/platform-roadmap#315]
### For Contributing Author:

This is the Primary Product Ticket for the following community contribution: New feature that will allow course instructors to manage certificates.

### Checklist prior to undergoing Product Review:

The following information is required in order for Product Managers to be able to review your pull request:

- [  ] Explanation of the problem being solved
- [  ] Description of how users will be impacted, and which users will be impacted
- [  ] Screenshots or video showing the functionality or fix, before and after
- [  ] Reproduction steps and/or testing steps

Only if necessary:

- [ ] If necessary, links to corresponding configuration changes
- [ ] If necessary, links to corresponding enablement changes, particularly waffle/toggle status details

### Related PRs

https://github.com/openedx/frontend-app-discussions/pull/574

-------

### For Product Manager doing the review:

What criteria should be analyzed from Product to approve a PR?

- The problem being solved by the feature or fix is clear.
- There is clarity on how the change or fix will impact the end user.
- It is clear that the change will not negatively impact users or other areas of the platform.
- The change is implemented comprehensively.
- Any changes to UI use the current, standard Paragon Design System: https://paragon-openedx.netlify.app/

**Comment by cassiezamparini** [comment]
@jmakowski1123 Is this something we're still looking at? is the ticket still valid?
