### ISSUE TITLE
New Certificates Page (Studio MFE conversion)

### ISSUE THREAD

**Issue by jmakowski1123** [openedx/platform-roadmap#317]
### Project Scope

**STATUS:** The Certificates page is currently being implemented.

The Certificates Page is part of the Course Authoring MFE.

The design files are here: https://www.figma.com/file/YeKFwSpyLaJFDs3f3p3TSa/Studio-1%3A1-mock-ups?type=design&node-id=0-1&mode=design&t=pbMclMlKB1pwEGkJ-0

### **Associated PRs:**

```[tasklist]
- [ ] https://github.com/openedx/frontend-app-course-authoring/pull/872
- [ ] https://github.com/openedx/edx-platform/pull/34339
- [ ] https://github.com/openedx/frontend-app-course-authoring/pull/992
```

**Comment by GlugovGrGlib** [comment]
@arbrandes All PRs are merged and the page was released in Redwood, can we close this issue
