### ISSUE TITLE
New Content Grouping Page (Studio MFE conversion)

### ISSUE THREAD

**Issue by jmakowski1123** [openedx/platform-roadmap#318]
### Project Scope

**STATUS:** The Content Grouping page is currently being implemented.

The Content Grouping Page is part of the Course Authoring MFE.

The design files are here: https://www.figma.com/file/YeKFwSpyLaJFDs3f3p3TSa/Studio-1%3A1-mock-ups?type=design&node-id=0-1&mode=design&t=pbMclMlKB1pwEGkJ-0

### **Associated PRs:**

```[tasklist]
- [ ] https://github.com/openedx/edx-platform/pull/34389
```

**Comment by jmakowski1123** [comment]
There is an open question as to whether the new page should support the Content Experiment feature, which was part of the legacy experience. Product is currently investigating the current status and usage of this feature and whether it aligns with the core offering. https://edx.readthedocs.io/projects/edx-partner-course-staff/en/latest/course_features/content_experiments/content_experiments_add.html

**Comment by arbrandes** [comment]
Looks like this one's done.
