### ISSUE TITLE
New Textbook page (Studio MFE conversion)

### ISSUE THREAD

**Issue by jmakowski1123** [openedx/platform-roadmap#319]
### Project Scope

**STATUS:** The Textbook page is currently being implemented.

The Textbook Page is part of the Course Authoring MFE.

The design files are here: https://www.figma.com/file/YeKFwSpyLaJFDs3f3p3TSa/Studio-1%3A1-mock-ups?type=design&node-id=0-1&mode=design&t=pbMclMlKB1pwEGkJ-0

### **Associated PRs:**

```[tasklist]
- [ ] https://github.com/openedx/frontend-app-course-authoring/pull/890
- [ ] https://github.com/openedx/edx-platform/pull/34388
```

**Comment by arbrandes** [comment]
Looks like this one's done!
