### ISSUE TITLE
New Course Outline page (Studio MFE conversion)

### ISSUE THREAD

**Issue by jmakowski1123** [openedx/platform-roadmap#320]
### Project Scope

**STATUS:** The Course Outline page is currently being implemented: https://openedx.atlassian.net/wiki/spaces/COMM/pages/3862560783/WBS+for+Course+Content+Outline+page

The Course Outline Page has been updated to include new Paragon components. In particular, updated elements include updated fonts, updated header and styling of course metadata fields, updated cards for each course section.

### Differences in the sub-header section with metadata

![Image](https://github.com/openedx/platform-roadmap/assets/95227019/fbf3eab7-2ce9-4b66-ade7-6b0ec794a60b)

The community implementation of this space will require some changes to ensure it is generalized and non-edx specific. This means:

- The "checklists" field should not be included in the community release. This is an edx.org specific feature.
- The video sharing field and dropdown should not be included in the community release. This is an edx.org specific feature.
- We should include the "manage tags" field, as per the designs here: https://www.figma.com/file/DmUC2e7BAoQsGDq4KgApPa?node-id=13204:34437&mode=design#677671141

The new Course Outline Page will contain net-new features not included in the legacy experience. This includes:

**New features associated with the Tagging project:**

- Three dot menu on the unit, subsection and section blocks with "manage tags" button
- Icon with # of tags displayed
- Manage tags button in the three dot menu
- New "manage tags" workflow from the course header space with course metadata displays

**New features associated with the Copy/Paste project:**

- Copy unit to clipboard
- Paste button
- What's in my clipboard status

These new features are documented here: https://openedx.atlassian.net/wiki/spaces/COMM/pages/3866460192/New+Additions+to+Course+Content+Outline

And in figma (see "tagging sections, subsections and courses": https://www.figma.com/file/DmUC2e7BAoQsGDq4KgApPa/Content-Tagging-MVP?type=design&node-id=11845-19907&mode=design&t=E6QZSuHBeIvuQdmH-0 

**New features associated with in-context discussions**

- Enable in-context discussions on units

The Course Outline Page is part of the Course Authoring MFE.

The design files are here: https://www.figma.com/file/YeKFwSpyLaJFDs3f3p3TSa/Studio-1%3A1-mock-ups?type=design&node-id=0-1&mode=design&t=pbMclMlKB1pwEGkJ-0

### **Associated PRs:**

**Comment by arbrandes** [comment]
Done (at least as far as I know).
