### ISSUE TITLE
Implement Open edX For Cats

### ISSUE THREAD

**Issue by sarina** [openedx/platform-roadmap#328]
### Abstract

Cats are great

### Context & Background

They're cats

### Scope & Approach

I think I can fit about 6 cats in my apartment

### Value & Impact

Cats make me happy

### Milestones and/or Epics

* Milestone 1: Acquire 3 more cats

### Named Release

Sumac

### Timeline

Think we can do this by EOY24

### Proposed By

Axim

**Comment by sarina** [comment]
![image](https://github.com/openedx/platform-roadmap/assets/1985317/4baa7f3a-8c9d-40fd-a8ad-64d865bce0e4)

c a t

**Comment by sarina** [comment]
![image](https://github.com/openedx/platform-roadmap/assets/1985317/a59b0c4e-11d7-448a-a352-3fa58c6ec038)

c a t (disgruntled)

**Comment by sarina** [comment]
![image](https://github.com/openedx/platform-roadmap/assets/1985317/7fd1d135-2e65-4de9-8e9e-b4eeef5952a6)

the author, with c a t

**Comment by sarina** [comment]
![image](https://github.com/openedx/platform-roadmap/assets/1985317/2c1f16f7-9490-4ca9-8353-499f2b9d681c)

a pile of c a t (also known as a "clowder")

**Comment by jmakowski1123** [comment]
APPROVED

**Comment by crathbun428** [comment]
Q-tip smashing that approve button
![IMG_0646](https://github.com/openedx/platform-roadmap/assets/57507106/0d32f449-a0c5-4c50-be4c-8a42a03b0a1b)

**Comment by mariajgrimaldi** [comment]
Diana supports
<img src="https://github.com/openedx/platform-roadmap/assets/64440265/218d9f9f-7b68-4b88-bd4d-b8b9b9072b02" alt="diana" width="500"/>

**Comment by pomegranited** [comment]
This could be Open edX's big differentiator.. I mean, how many LMS are accessible to cats?
