### ISSUE TITLE
Mongo 7 Upgrade

### ISSUE THREAD

**Issue by jmakowski1123** [openedx/platform-roadmap#339]
A ticket to redirect to all documentation related to the Mongo 7 upgrade.''

https://github.com/openedx/public-engineering/issues/245

**Comment by kdmccormick** [comment]
@jmakowski1123 @feanil This was merged to master: https://github.com/openedx/public-engineering/issues/245

Should we close this?

**Comment by feanil** [comment]
@kdmccormick I'm not sure what the product roadmap process is but you're right that this has shipped to edx-platform and to cs_comment_service so the work is complete and will be available in Redwood.

@jmakowski1123 let me know what the next step should be on the roadma side, should I just close the issue? Inform you/Someone Else?

**Comment by sarina** [comment]
Closing as this is marked "Shipped" on the PR board 🎉
