### ISSUE TITLE
[Product Pull Request] feat: Support web-based LMS OAuth

### ISSUE THREAD

**Issue by jmakowski1123** [openedx/platform-roadmap#345]
Master ticket for the project.

Child PRs:

- [ ] https://github.com/openedx/openedx-app-ios/pull/65

**Comment by itsjeyd** [comment]
@xitij2000 @Kelketek If I understand correctly (?), https://github.com/openedx/openedx-app-android/pull/190 is closely related to https://github.com/openedx/openedx-app-ios/pull/65, the only PR listed as a child of this roadmap item so far.

Would it make sense to add https://github.com/openedx/openedx-app-android/pull/190 [above](https://github.com/openedx/platform-roadmap/issues/345#issue-2214320903)?

CC @jmakowski1123

**Comment by xitij2000** [comment]
> @xitij2000 @Kelketek If I understand correctly (?), [openedx/openedx-app-android#190](https://github.com/openedx/openedx-app-android/pull/190) is closely related to [openedx/openedx-app-ios#65](https://github.com/openedx/openedx-app-ios/pull/65), the only PR listed as a child of this roadmap item so far.
> 
> Would it make sense to add [openedx/openedx-app-android#190](https://github.com/openedx/openedx-app-android/pull/190) to the list [above](https://github.com/openedx/platform-roadmap/issues/345#issue-2214320903)?
> 
> CC @jmakowski1123

Yes, I think that is the latest version of the "login-via-LMS" work.

**Comment by mphilbrick211** [comment]
Hi all, just looking for an update here (@jmakowski1123)

**Comment by Kelketek** [comment]
@mphilbrick211 The sponsoring organization decided not to move this forward to completion, unfortunately, so it's stuck.

**Comment by itsjeyd** [comment]
@Kelketek @mphilbrick211 For https://github.com/openedx/openedx-app-android/pull/190 specifically, I think we might actually have a way forward.

@xitij2000 Does the new PR that you created a couple days ago (https://github.com/openedx/openedx-app-android/pull/371) fully replace that PR?

**Comment by xitij2000** [comment]
@itsjeyd Yes, I should perhaps have updated the same PR, however, this one is the same code rebased to the latest main branch.

**Comment by itsjeyd** [comment]
@xitij2000 OK, thanks for confirming 👍 

@mphilbrick211 @jmakowski1123 Could we get https://github.com/openedx/openedx-app-android/pull/371 added to the list of child PRs for this feature ticket in the [description](https://github.com/openedx/platform-roadmap/issues/345#issue-2214320903) above?

CC @Kelketek

**Comment by mphilbrick211** [comment]
Is there an update on this?

**Comment by Kelketek** [comment]
@mphilbrick211 The Android feature has apparently been merged, but [I haven't gotten confirmation on it for the iOS app](https://github.com/openedx/openedx-app-ios/issues/212#issuecomment-2528562228).

**Comment by Kelketek** [comment]
@jmakowski1123 Did you mean to close this ticket? Android got this feature but I don't think iOS did. The PR on this ticket hasn't been merged either.
