### ISSUE TITLE
[Product Pull Request] feat: course about page markup and styles improvements

### ISSUE THREAD

**Issue by jmakowski1123** [openedx/platform-roadmap#346]
This is a Master ticket for this project.

Child PRs:

- [ ] https://github.com/openedx/edx-platform/pull/33712

**Comment by mphilbrick211** [comment]
related backport: https://github.com/openedx/edx-platform/pull/33791

**Comment by itsjeyd** [comment]
@jmakowski1123 @mphilbrick211 It looks like this is done; the PRs for it have been merged. Can we close this ticket and move it to Shipped on the [roadmap](https://github.com/orgs/openedx/projects/4/views/20)?
