### ISSUE TITLE
[Product Pull Request] feat: Added correct image for FB sharing

### ISSUE THREAD

**Issue by jmakowski1123** [openedx/platform-roadmap#347]
This is a Master Ticket for this project.

Child PRs:

- [ ] https://github.com/openedx/edx-platform/pull/33784
- [ ] https://github.com/openedx/edx-platform/pull/33785

**Comment by mphilbrick211** [comment]
Hi @jmakowski1123! I think this is another child ticket for this item: https://github.com/openedx/edx-platform/pull/34919

Is there any update on reviews for these?

**Comment by mphilbrick211** [comment]
> Hi @jmakowski1123! I think this is another child ticket for this item: [openedx/edx-platform#34919](https://github.com/openedx/edx-platform/pull/34919)
> 
> Is there any update on reviews for these?

@jmakowski1123 following up on this!

**Comment by mphilbrick211** [comment]
> > Hi @jmakowski1123! I think this is another child ticket for this item: [openedx/edx-platform#34919](https://github.com/openedx/edx-platform/pull/34919)
> > Is there any update on reviews for these?
> 
> @jmakowski1123 following up on this!

Apologies - this was approved in the original master pull request, so I think this roadmap ticket can be closed.
