### ISSUE TITLE
[Product Pull Request] fix: Fix discussions and notifications sidebars visibility with big amount of units

### ISSUE THREAD

**Issue by jmakowski1123** [openedx/platform-roadmap#348]
This is a Master ticket for the project.

Child PRs:

- [ ] https://github.com/openedx/frontend-app-learning/pull/1333
- [ ] https://github.com/openedx/frontend-app-learning/pull/1334

**Comment by jmakowski1123** [comment]
Sometime between now and Sumac in December, we are very likely to be removing the horizontal navigation bar entirely in favor of the new lefthand sidebar nav, which will be released in Redwood. I'd suggest tabling this as it will be solved by default when we remove it.

**Comment by itsjeyd** [comment]
Hey @Lunyachek, considering @jmakowski1123's comment above, do you think it would make sense to close https://github.com/openedx/frontend-app-learning/pull/1333 and https://github.com/openedx/frontend-app-learning/pull/1334 (Quince backport)?

**Comment by jmakowski1123** [comment]
I'm going to close this proposal from a product pov. If the new sidebar enhancements don't meet your needs by Sumac, we can revisit.

**Comment by itsjeyd** [comment]
@jmakowski1123 Just to understand better from a process perspective, does the `ready for product review` label still make sense for this feature ticket?

**Comment by sarina** [comment]
Closing as this is marked "Abandoned" on the PR board. It may always be re-opened if needed.
