### ISSUE TITLE
[Pull Request]: Remove "Add a post" button when discussion is restricted for specific roles

### ISSUE THREAD

**Issue by farhaanbukhsh** [openedx/platform-roadmap#391]
### Abstract

The issues we faced were when the discussions were restricted the "Add a post" button was shown to global staff and superusers but when they create a post the MFE doesn't let them create the post and the backend raises a 403 error.

### Context & Background (in brief, if a Product Proposal is linked above)

The issues we faced were when the discussions were restricted the "Add a post" button was shown to global staff and superusers but when they create a post the MFE doesn't let them create the post and the backend raises a 403 error.

This happens because there exists a mismatch in permission on who can create a post when discussion is restricted.

There is a mismatch in the roles, hence I am taking edx-platform as my source of truth and what the implementation should be hence I dug a little deeper. From edx-platform we can confirm that only the user who has one of the following roles Discussion Admin, Moderator, Community TA or Group Moderator are allowed to make the post even during the restriction period. The proof for this is:

Docstring for [has_discussion_privileges](https://github.com/openedx/edx-platform/blob/master/lms/djangoapps/discussion/django_comment_client/utils.py#L116)
    
This proves that [course staff doesn't have priviledge](https://github.com/openedx/edx-platform/blob/master/lms/djangoapps/discussion/django_comment_client/tests/test_utils.py#L110)

The MFE uses api at <LMS_URL>/api/discussion/v2/courses/<COURSE_ID>/ which uses [get_course](https://github.com/openedx/edx-platform/blob/master/lms/djangoapps/discussion/rest_api/api.py#L282) and here if the user has has_moderation_privileges or is_group_ta then they can post on a restricted discussion.

Hence on the MFE  we need to change [isPriviledge](https://github.com/openedx/frontend-app-discussions/blob/master/src/discussions/data/hooks.js#L228) to use:

userHasModerationPrivileges || isUserGroupTA

and we should be aligned with the original idea.

### Scope & Approach (in brief, if a Product Proposal is linked above)

This is a fix led by OpenCraft since the behavior already existed in the Legacy UI but they were missing in MFE.

### Value & Impact (in brief, if a Product Proposal is linked above)

This brings the permission in the edx-platform inline with the usage in MFE.

### Milestones and/or Epics

PR: https://github.com/openedx/frontend-app-discussions/pull/742

### Named Release

Teak

### Timeline (in brief, if a Product Proposal is linked above)

It is ready to merge.

### Proposed By

OpenCraft

**Comment by farhaanbukhsh** [comment]
@cassiezamparini @itsjeyd @marcotuts any updates here?

**Comment by cassiezamparini** [comment]
@farhaanbukhsh Correct me if I'm wrong - but has this proposal had a coordinator assigned to it? That way the coordinator can push for feedback.

**Comment by farhaanbukhsh** [comment]
@cassiezamparini nope, how do I find a coordinator?

**Comment by cassiezamparini** [comment]
See the process [here](https://openedx.atlassian.net/wiki/spaces/COMM/pages/3875962884/How+to+submit+an+open+source+contribution+for+Product+Review). So you can also be the coordinator - see Step 1 "d". Maybe that's best.

Then see Step 2 of the process if you'd like to take the role on :)

**Comment by farhaanbukhsh** [comment]
@cassiezamparini I think I can do it :)  so there are no objections here or this needs to be discussed more? Since @xitij2000 who is a CC for the repo has already approved it.

**Comment by cassiezamparini** [comment]
@farhaanbukhsh It looks like it may be good to go seen as you've had one +1 from an external organization as well. This is a bit of a grey area right now... how many reviewers are enough 😆 If you'd feel more comfortable having more reviews, you can always ping people directly on Github.  

If you go ahead, I would just update the statuses accordingly and add it to the community release sheet when you get there 😄 And also please let me know if you have any queries about the [Product Process](https://openedx.atlassian.net/wiki/spaces/COMM/pages/3875962884/How+to+submit+an+open+source+contribution+for+Product+Review)! Always wanting to improve it!

**Comment by cassiezamparini** [comment]
@farhaanbukhsh All learning for all of us! And the more you question the better we can make the process :)

**Comment by xitij2000** [comment]
@farhaanbukhsh  Noted, will merge once the PR is rebased.

**Comment by sarina** [comment]
I signed up to coordinate this, it seems good to me and has +1's from a varying group. I think this is good to merge!

**Comment by farhaanbukhsh** [comment]
@sarina  The PR is merged we are good to go here. cc; @cassiezamparini
