### ISSUE TITLE
Modernized Course Authoring Environment

### ISSUE THREAD

**Issue by e0d** [openedx/platform-roadmap#43]
Master issue for work related to modernizing and improving the Studio authoring environment.

Includes:
https://github.com/openedx/platform-roadmap/issues/49
https://github.com/openedx/platform-roadmap/issues/48
https://github.com/openedx/platform-roadmap/issues/47
https://github.com/openedx/platform-roadmap/issues/46

**Comment by jmakowski1123** [comment]
Placeholder for tickets listed above related to Studio enhancements - closing to avoid confusion
