### ISSUE TITLE
Official Language Support for Open edX Platform

### ISSUE THREAD

**Issue by e0d** [openedx/platform-roadmap#66]
Create a working group to focus the efforts on the Open edX translator community to complete translations for the 10 most critical languages based on number of worldwide speakers.  Create a sustainable process for keeping translations up to date for each Open edX release.

AC:
- Proposal for 10 officially supported languages.  These languages were chosen based on a combination of factors including the number of speakers worldwide, the number of existing translators, the engagement of existing translators.
  - Spanish (es-419)
  - Portuguese (pt)
  - Italian (it)
  - German (de)
  - French (ca) 
  - Ukrainian (uk)
  - Russian (ru)
  - Mandarin (cmn)
  - Hindi (hi)
  - Arabic (ar)
- Publish requirements for a team that backs a supported language
  - how many translators
  - how many reviewers
  - how many coordinators
- Establish a working group to coordinate efforts and focus community.

**Comment by jmakowski1123** [comment]
Transifex Working Group Confluence Page and related documentation: https://openedx.atlassian.net/wiki/spaces/COMM/pages/3157524644/Transifex+Working+Group

**Comment by jmakowski1123** [comment]
The Transifex Working Group was created on August 18th, 2021 as a spin off from the existing Open edX Marketing Working Group. The Transifex Working Group is open to all members of the community and currently consists of Open edX community members, who are assisting in centralizing our collaboration efforts on crowdsourced translations and reviews of translated content, in an effort to further enhance our platform & website localization strategy. A successfully executed crowdsourced translation strategy, guided by the Transifex Working Group, will not only aid in producing higher quality translated content, but will also lead to additional intrinsic values, such as allowing the community to help produce a more robust global product, while functioning as curators for new content, 100% completion on strings translated for all Open edX software releases, a successfully and accurately translated website, and translated user documentation to aid in the increased global adoption of the Open edX platform.

Transifex Working Group Confluence Page and related documentation: https://openedx.atlassian.net/wiki/spaces/COMM/pages/3157524644/Transifex+Working+Group
