### ISSUE TITLE
Working Ecommerce in Maple

### ISSUE THREAD

**Issue by e0d** [openedx/platform-roadmap#69]
BTR has identified several issues with the ecommerce functionality that prevent it from working with the Maple release.  This epic will track all the issues that must be resolved to have working ecommerce in Maple.

**Comment by regisb** [comment]
So far I labelled these issues as "help wanted" and "affects:maple" in the BTR working group project board: https://github.com/openedx/build-test-release-wg/projects/1?card_filter_query=label%3A%22help+wanted%22+label%3Aaffects%3Amaple

**Comment by regisb** [comment]
From my perspective, the only item left as a TODO is to modify the payment form abstraction to make it possible/easy to implement and plug custom payment processors: https://github.com/openedx/build-test-release-wg/issues/74
