### ISSUE TITLE
Audit Open edX Code Supply chain and suggest improvements.

### ISSUE THREAD

**Issue by feanil** [openedx/platform-roadmap#70]
Some questions but not necessarily comprehensive:

* How are we ensuring that we stay up-to-date with 3rd party security updates?
* Are we signing our own packages to prevent malicious actors from faking out our operators?
* Similarly, are we validating signatures of upstream packages?
* etc.

**Comment by jmakowski1123** [comment]
Prioritizing as this ties to upcoming work to spec comprehensive set of tCRIL services -

**Comment by jmakowski1123** [comment]
Scope as part of tCRIL Services

**Comment by feanil** [comment]
https://slsa.dev/ might be a useful spec to look at when doing this assessment.

**Comment by jmakowski1123** [comment]
@feanil This has been on the community roadmap backlog for 2 years. I'm trimming the backlog to only include stuff we're going to accomplish in 2024-25. I'm going to close it for now. If it's something the maintenance WG will pursue in the future, please re-open it (or start a newer ticket) and we can get it back on the boarc.
